#!/usr/bin/env node
// GENERATED by scripts/build-plugins.mjs; hook sources 3403533713cd84e9

// hooks/lakeday-hook.mjs
import { spawn as nodeSpawn } from "node:child_process";
import fs6 from "node:fs";
import path5 from "node:path";
import { fileURLToPath } from "node:url";

// hooks/lib/config.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
var DEFAULT_API_BASE_URL = "https://api.lakeday.ai";
function lakedayHome(env = process.env) {
  return env.LAKEDAY_HOME || path.join(os.homedir(), ".lakeday");
}
function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}
function findProjectConfig(cwd) {
  let dir = cwd ? path.resolve(cwd) : process.cwd();
  for (; ; ) {
    const candidate = path.join(dir, ".lakeday", "agent-skills.json");
    if (fs.existsSync(candidate)) return { file: candidate, dir, data: readJson(candidate) ?? {} };
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
function projectSlug(cwd) {
  const base = path.basename(path.resolve(cwd || process.cwd())) || "project";
  const slug = base.toLowerCase().replace(/[^a-z0-9_.-]+/g, "-").replace(/^[^a-z0-9]+/, "");
  return (slug || "project").slice(0, 60);
}
function resolveConfig({ cwd, env = process.env } = {}) {
  const project = findProjectConfig(cwd);
  const user = readJson(path.join(lakedayHome(env), "agent-skills.json")) ?? {};
  const merged = { ...user, ...project?.data ?? {} };
  const token = env.LAKEDAY_API_KEY || env.LAKEDAY_API_TOKEN || env.LAKEDAY_TOKEN || null;
  const tenant = env.LAKEDAY_TENANT_ID || merged.tenant_id || null;
  const baseUrl = (env.LAKEDAY_API_BASE_URL || merged.api_base_url || DEFAULT_API_BASE_URL).replace(/\/+$/, "");
  const slug = merged.project || projectSlug(project?.dir ?? cwd);
  const config = {
    // Finalized by the entry point once OAuth and tenant discovery ran.
    enabled: false,
    token,
    tenant,
    baseUrl,
    home: lakedayHome(env),
    project: slug,
    // Entity IDs the hooks maintain. Personal IDs are prefixed with the caller's
    // OS owner prefix at runtime; shared IDs are used verbatim and require
    // collection grants on the deployment's Entity Worker.
    projectEntity: merged.project_entity || `repo:${slug}`,
    sharedEntities: merged.shared_entities === true,
    // ALWAYS policy knobs.
    enforceDecisions: merged.enforce_decisions !== false,
    maxStopBlocksPerTurn: Number.isInteger(merged.max_stop_blocks_per_turn) ? merged.max_stop_blocks_per_turn : 1,
    contextBudgetChars: Number.isInteger(merged.context_budget_chars) ? merged.context_budget_chars : 16e3,
    recallPriorDecisions: merged.recall_prior_decisions !== false,
    debug: env.LAKEDAY_HOOK_DEBUG === "1" || merged.debug === true,
    sourceFiles: { project: project?.file ?? null, user: path.join(lakedayHome(env), "agent-skills.json") }
  };
  return config;
}

// hooks/lib/auth.mjs
import { execFile as nodeExecFile } from "node:child_process";
import { createHash } from "node:crypto";
import fs2 from "node:fs";
import path2 from "node:path";
import { promisify } from "node:util";
var execFileAsync = promisify(nodeExecFile);
var CLI_TIMEOUT_MS = 1e4;
var CLI_MAX_BUFFER = 256 * 1024;
function readJson2(file) {
  try {
    return JSON.parse(fs2.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}
function writeJson(file, value) {
  fs2.mkdirSync(path2.dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  fs2.writeFileSync(tmp, JSON.stringify(value, null, 2), { mode: 384 });
  fs2.renameSync(tmp, file);
}
function cliPath(env) {
  return env.LAKEDAY_CLI_PATH || env.LAKEDAY_CLI || "lk";
}
function parseCliToken(stdout) {
  const text = String(stdout ?? "").trim();
  if (!text) return null;
  let result;
  try {
    result = JSON.parse(text);
  } catch {
    return null;
  }
  if ((result?.type === "oauth" || result?.type === "api_token") && typeof result.token === "string" && result.token) {
    return result;
  }
  if (result?.type === "api_key") return { type: "api_key" };
  return null;
}
function safeErrorCode(error) {
  const code = error?.code;
  if (Number.isInteger(code)) return `exit ${code}`;
  if (typeof code === "string" && ["ENOENT", "EACCES", "ETIMEDOUT", "ERR_CHILD_PROCESS_STDIO_MAXBUFFER"].includes(code)) {
    return code;
  }
  if (typeof error?.signal === "string" && /^SIG[A-Z0-9]+$/.test(error.signal)) {
    return `signal ${error.signal}`;
  }
  return "unavailable";
}
async function cliAuthToken({
  baseUrl,
  cwd = process.cwd(),
  env = process.env,
  execFile: execFileImpl = execFileAsync,
  log = () => {
  }
}) {
  const commandEnv = {
    ...process.env,
    ...env,
    LAKEDAY_API_BASE_URL: baseUrl
  };
  try {
    const { stdout } = await execFileImpl(
      cliPath(env),
      ["auth", "token", "--json"],
      {
        cwd,
        env: commandEnv,
        encoding: "utf8",
        timeout: CLI_TIMEOUT_MS,
        maxBuffer: CLI_MAX_BUFFER
      }
    );
    const result = parseCliToken(stdout);
    if (result?.token) return { token: result.token, source: "lk auth token" };
    if (result?.type === "api_key") {
      log("lk auth token returned an API key/email pair; hooks need a bearer token");
    }
  } catch (error) {
    log(`lk auth token failed (${safeErrorCode(error)})`);
  }
  return null;
}
async function resolveToken({
  baseUrl,
  home: _home,
  cwd = process.cwd(),
  env = process.env,
  execFile: execFileImpl = execFileAsync,
  log = () => {
  }
}) {
  const envToken = env.LAKEDAY_API_KEY || env.LAKEDAY_API_TOKEN || env.LAKEDAY_TOKEN;
  if (envToken) return { token: envToken, source: "env" };
  const fromCli = await cliAuthToken({
    baseUrl,
    cwd,
    env,
    execFile: execFileImpl,
    log
  });
  if (fromCli) return fromCli;
  return {
    token: null,
    source: "none",
    hint: "run `lk login` first, or set LAKEDAY_API_KEY for a service identity"
  };
}
function tokenFingerprint(token) {
  return createHash("sha256").update(String(token)).digest("hex").slice(0, 32);
}
async function discoverTenant({
  baseUrl,
  token,
  home,
  fetch: fetchImpl = globalThis.fetch,
  log = () => {
  }
}) {
  const cacheFile = path2.join(home, "agent-skills", "cache", "tenants.json");
  const cache = readJson2(cacheFile) ?? {};
  const cacheKey = `${baseUrl}#${tokenFingerprint(token)}`;
  if (cache[cacheKey]?.tenant && Date.now() - (cache[cacheKey].at ?? 0) < 24 * 3600 * 1e3) {
    return cache[cacheKey].tenant;
  }
  const response = await fetchImpl(`${baseUrl}/v1/me`, {
    headers: { authorization: `Bearer ${token}`, accept: "application/json" }
  });
  if (!response.ok) {
    log(`/v1/me failed: HTTP ${response.status}`);
    return null;
  }
  const me = await response.json();
  const deployments = [];
  for (const organization of Array.isArray(me.organizations) ? me.organizations : []) {
    for (const deployment of Array.isArray(organization?.deployments) ? organization.deployments : []) {
      if (deployment && typeof deployment.id === "string") deployments.push(deployment.id);
    }
  }
  if (deployments.length !== 1) {
    log(`tenant discovery: ${deployments.length} deployments visible; set tenant_id`);
    return null;
  }
  cache[cacheKey] = { tenant: deployments[0], at: Date.now() };
  writeJson(cacheFile, cache);
  return deployments[0];
}

// ../lakeday/sdk/packages/worker-js/src/learning.js
var LEARNING_MODES = Object.freeze(["always", "agentic", "off"]);
var MAX_LINE = 240;
function clip(text, max = MAX_LINE) {
  if (text == null) return "";
  const single = String(text).replace(/\s+/g, " ").trim();
  return single.length > max ? `${single.slice(0, max - 1)}\u2026` : single;
}
function sanitizeId(value, max = 100) {
  const cleaned = String(value).replace(/[^a-zA-Z0-9_.:-]+/g, "-").replace(/^[^a-zA-Z0-9]+/, "");
  return (cleaned || "x").slice(0, max);
}
var CONSEQUENTIAL_TOOLS = /* @__PURE__ */ new Set([
  "deploy_worker",
  "delete_worker",
  "deploy_pipeline",
  "run_pipeline",
  "stream_send",
  "stream_load",
  "transform_commit",
  "sink_commit",
  "lake_ingest",
  "create_collection",
  "collection_grant",
  "assign_data_source",
  "set_table_policy",
  "create_dashboard",
  "update_dashboard",
  "delete_dashboard"
]);
var MEASUREMENT_TOOLS = /* @__PURE__ */ new Set([
  "query_sql",
  "inspect_dashboard",
  "evaluate_dashboard",
  "sink_read",
  "ui_render"
]);
var RECORDING_TOOLS = /* @__PURE__ */ new Set([
  "session_decide",
  "session_outcome",
  "entity_fact",
  "entity_link",
  "session_append",
  "session_context"
]);
var CODE_TOOLS = /* @__PURE__ */ new Set([
  "Edit",
  "Write",
  "MultiEdit",
  "NotebookEdit",
  "apply_patch"
]);
function normalizeToolCall({ name, input, output, error, serverName }) {
  let toolName = name ?? "";
  let toolInput = input && typeof input === "object" ? input : {};
  if (toolName === "product_tool" && typeof toolInput.name === "string") {
    toolName = toolInput.name;
    toolInput = toolInput.arguments && typeof toolInput.arguments === "object" ? toolInput.arguments : {};
  }
  const lakedayTool = lakedayToolName(toolName, serverName);
  const parsed = parseMaybeJson(output);
  return {
    name: toolName,
    lakedayTool,
    input: toolInput,
    output: parsed,
    error: error ?? toolError(parsed)
  };
}
function lakedayToolName(name, serverName) {
  if (!name) return null;
  if (serverName && serverName !== "lakeday") return null;
  let candidate = name;
  const mcp = /^mcp__([^_]+(?:_[^_]+)*)__(.+)$/.exec(name);
  if (mcp) {
    if (mcp[1] !== "lakeday") return null;
    candidate = mcp[2];
  } else if (name.includes("__")) {
    const parts = name.split("__");
    if (parts[0] !== "lakeday") return null;
    candidate = parts.slice(1).join("__");
  } else if (name.startsWith("lakeday.")) {
    candidate = name.slice("lakeday.".length);
  }
  if (CONSEQUENTIAL_TOOLS.has(candidate) || MEASUREMENT_TOOLS.has(candidate) || RECORDING_TOOLS.has(candidate) || /^(entity|session|query|stream|sink|transform|list|get|whoami|invoke|render|validate|package|ui|web|browser)_?[a-z_]*$/.test(
    candidate
  ))
    return candidate;
  return null;
}
function parseMaybeJson(value) {
  if (typeof value !== "string") return value;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}
function toolError(output) {
  if (output == null) return null;
  if (typeof output === "string")
    return /^(error|Error:|\{"error"|HTTP [45]\d\d)/m.test(output.trim()) ? output.slice(0, 500) : null;
  if (typeof output === "object") {
    if (output.isError === true || output.is_error === true)
      return summarize(output);
    if (typeof output.error === "string") return output.error.slice(0, 500);
    if (typeof output.status === "number" && output.status >= 400)
      return summarize(output);
    if (output.structuredContent && typeof output.structuredContent.error === "string")
      return output.structuredContent.error.slice(0, 500);
  }
  return null;
}
function summarize(value) {
  try {
    return JSON.stringify(value).slice(0, 500);
  } catch {
    return String(value).slice(0, 500);
  }
}
function classifyTool(tool) {
  if (!tool) return "other";
  if (tool.lakedayTool) {
    if (RECORDING_TOOLS.has(tool.lakedayTool)) return "recording";
    if (CONSEQUENTIAL_TOOLS.has(tool.lakedayTool)) return "consequential";
    if (MEASUREMENT_TOOLS.has(tool.lakedayTool)) return "measurement";
    return "read";
  }
  if (CODE_TOOLS.has(tool.name)) return "code";
  if (tool.name === "Bash" && typeof tool.input?.command === "string" && /\bgit\s+(commit|push|merge|rebase|tag)\b/.test(tool.input.command))
    return "consequential";
  return "other";
}
function tablesInSql(sql) {
  if (typeof sql !== "string") return [];
  const found = /* @__PURE__ */ new Set();
  const re = /\b(?:from|join)\s+([a-zA-Z_][a-zA-Z0-9_.]*)/gi;
  let m;
  while (m = re.exec(sql)) {
    const name = m[1].split(".").pop();
    if (!["select", "lateral", "unnest", "values"].includes(name.toLowerCase()))
      found.add(name);
  }
  return [...found].slice(0, 6);
}
function structuredOf(output) {
  if (!output || typeof output !== "object") return {};
  if (output.structuredContent && typeof output.structuredContent === "object")
    return output.structuredContent;
  return output;
}
function evidenceFor(tool) {
  const t = tool.lakedayTool;
  const input = tool.input ?? {};
  const structured = structuredOf(tool.output);
  const version = structured.table_version ?? structured.snapshot ?? structured.version ?? null;
  const refs = [];
  const dataset = (id, v) => refs.push({
    kind: "dataset",
    id: sanitizeId(id),
    ...v != null ? { version: String(v) } : {}
  });
  switch (t) {
    case "run_pipeline":
    case "deploy_pipeline":
      if (input.sink_table) dataset(input.sink_table, version);
      else if (structured.sink_table) dataset(structured.sink_table, version);
      break;
    case "sink_commit":
      if (input.batch?.table) dataset(input.batch.table, version);
      break;
    case "lake_ingest":
      if (input.table) dataset(input.table, version);
      break;
    case "stream_load":
      if (input.stream) dataset(input.stream, version);
      if (input.source ?? input.url)
        refs.push({
          kind: "url",
          id: String(input.source ?? input.url).slice(0, 120)
        });
      break;
    case "query_sql":
      for (const table of tablesInSql(input.sql)) dataset(table, version);
      break;
    case "inspect_dashboard":
    case "evaluate_dashboard":
    case "render_dashboard":
      if (input.id)
        refs.push({ kind: "entity", id: `dashboard:${sanitizeId(input.id)}` });
      break;
    default:
      break;
  }
  return refs.slice(0, 8);
}
function subjectsFor(tool) {
  const t = tool.lakedayTool;
  const input = tool.input ?? {};
  const out = [];
  if (t === "deploy_pipeline" || t === "run_pipeline")
    out.push(`pipeline:${sanitizeId(input.name ?? "")}`);
  if (t === "deploy_worker" || t === "delete_worker" || t === "invoke_worker")
    out.push(`worker:${sanitizeId(input.worker ?? "")}`);
  if (t === "create_dashboard")
    out.push(`dashboard:${sanitizeId(input.name ?? "")}`);
  if (t === "update_dashboard" || t === "delete_dashboard")
    out.push(`dashboard:${sanitizeId(input.id ?? "")}`);
  return out.filter((s) => !s.endsWith(":"));
}
function describeLakedayCall(name, input) {
  switch (name) {
    case "query_sql":
      return `query_sql: ${input.sql ?? ""}`;
    case "deploy_pipeline":
      return `deploy_pipeline ${input.name}: ${input.source_stream} \u2192 ${input.output_stream} \u2192 ${input.sink_table}`;
    case "run_pipeline":
      return `run_pipeline ${input.name}`;
    case "stream_send":
      return `stream_send ${input.stream}: ${Array.isArray(input.events) ? input.events.length : "?"} events`;
    case "stream_load":
      return `stream_load ${input.stream} \u2190 ${input.source ?? input.url ?? ""}`;
    case "lake_ingest":
      return `lake_ingest ${input.table}: ${Array.isArray(input.rows) ? input.rows.length : "?"} rows`;
    case "deploy_worker":
      return `deploy_worker ${input.worker}`;
    case "create_dashboard":
      return `create_dashboard ${input.name}`;
    case "update_dashboard":
      return `update_dashboard ${input.id}`;
    case "set_table_policy":
      return `set_table_policy ${input.collection}/${input.table_name} as ${input.sql_alias}`;
    case "collection_grant":
      return `collection_grant ${input.collection} ${input.role}${input.revoke ? " (revoke)" : ""} \u2192 ${input.email ?? input.membership_id ?? ""}`;
    case "assign_data_source":
      return `assign_data_source ${input.collection} \u2190 ${input.worker}/${input.binding}/${input.source_name ?? input.object ?? ""}`;
    case "invoke_worker":
      return `invoke_worker ${input.worker} ${input.method ?? "GET"} ${input.path ?? "/"}`;
    default:
      return `${name} ${clip(JSON.stringify(stripLarge(input)), 150)}`;
  }
}
function describeGenericCall(name, input) {
  if (name === "Bash") return `Bash: ${input.command ?? ""}`;
  if (CODE_TOOLS.has(name))
    return `${name}: ${input.file_path ?? input.path ?? ""}`;
  return `${name}`;
}
function stripLarge(input) {
  const out = {};
  for (const [k, v] of Object.entries(input ?? {})) {
    if (typeof v === "string" && v.length > 120) out[k] = `${v.slice(0, 117)}\u2026`;
    else if (Array.isArray(v)) out[k] = `[${v.length} items]`;
    else if (v && typeof v === "object") out[k] = "{\u2026}";
    else out[k] = v;
  }
  return out;
}
function toolEventData(tool, harness) {
  const input = tool.input ?? {};
  const label = tool.lakedayTool ? describeLakedayCall(tool.lakedayTool, input) : describeGenericCall(tool.name, input);
  const data = {
    type: "tool.result",
    tool: tool.lakedayTool ?? tool.name,
    ...harness ? { harness } : {},
    label: clip(label, 200),
    ok: !tool.error
  };
  if (tool.error) data.error = clip(tool.error, 300);
  const evidence = evidenceFor(tool);
  if (evidence.length) data.evidence = evidence;
  const subjects = subjectsFor(tool);
  if (subjects.length) data.subjects = subjects;
  return data;
}
function externalDatasetId(source) {
  const s = String(source);
  try {
    const url = new URL(s);
    return `${url.protocol.replace(":", "")}-${url.host}${url.pathname}`.replace(
      /\/+$/,
      ""
    );
  } catch {
    return s;
  }
}
function provenancePlan(tool, { sessionId, projectEntity } = {}) {
  if (!tool?.lakedayTool || tool.error) return [];
  const input = tool.input ?? {};
  const plan = [];
  const session = sessionId ? { session_id: sessionId } : {};
  const ensureEntity = (id, type, name, extra = {}) => plan.push({
    op: "ensure-entity",
    id,
    data: { type, name, ...extra, ...session }
  });
  const link = (from, id, predicate, target) => plan.push({
    op: "link",
    entity: from,
    data: { id: sanitizeId(id), predicate, target, ...session }
  });
  switch (tool.lakedayTool) {
    case "deploy_pipeline": {
      const name = sanitizeId(input.name ?? "");
      if (!name) break;
      const pipeline = `pipeline:${name}`;
      const source = `dataset:${sanitizeId(input.source_stream ?? "")}`;
      const table = `dataset:${sanitizeId(input.sink_table ?? "")}`;
      ensureEntity(pipeline, "pipeline", input.name, {
        transform_worker: `${input.name}-transform`,
        sink_worker: `${input.name}-sink`,
        cron: input.cron ?? null
      });
      ensureEntity(source, "dataset", input.source_stream, {
        source_kind: "stream"
      });
      ensureEntity(table, "dataset", input.sink_table, {
        source_kind: "lance_table"
      });
      link(pipeline, `reads-${name}`, "reads_from", {
        kind: "entity",
        id: source
      });
      link(pipeline, `writes-${name}`, "writes_to", {
        kind: "entity",
        id: table
      });
      link(table, `produced-by-${name}`, "produced_by", {
        kind: "entity",
        id: pipeline
      });
      if (projectEntity)
        link(projectEntity, `owns-pipeline-${name}`, "owns", {
          kind: "entity",
          id: pipeline
        });
      break;
    }
    case "run_pipeline": {
      const name = sanitizeId(input.name ?? "");
      const structured = structuredOf(tool.output);
      const table = structured.sink_table ?? input.sink_table;
      const version = structured.table_version ?? structured.snapshot ?? null;
      if (!name || !table) break;
      link(
        `pipeline:${name}`,
        `ran-${name}-${version ?? "latest"}`,
        "produced",
        {
          kind: "dataset",
          id: sanitizeId(table),
          ...version != null ? { version: String(version) } : {}
        }
      );
      break;
    }
    case "stream_load": {
      const stream = sanitizeId(input.stream ?? "");
      const source = input.source ?? input.url;
      if (!stream || !source) break;
      const streamEntity = `dataset:${stream}`;
      const external = `dataset:${sanitizeId(externalDatasetId(source))}`;
      ensureEntity(external, "dataset", String(source).slice(0, 200), {
        source_kind: "external",
        uri: String(source).slice(0, 500),
        format: input.format ?? null
      });
      ensureEntity(streamEntity, "dataset", input.stream, {
        source_kind: "stream"
      });
      link(streamEntity, `loaded-from-${stream}`, "loaded_from", {
        kind: "entity",
        id: external
      });
      break;
    }
    case "create_dashboard": {
      const name = sanitizeId(input.name ?? "");
      if (!name) break;
      const dashboard = `dashboard:${name}`;
      ensureEntity(dashboard, "dashboard", input.name, {
        deployment_id: input.deployment_id ?? null
      });
      const queries = input.document?.queries ?? {};
      for (const q of Object.values(queries))
        for (const table of tablesInSql(q?.sql))
          link(dashboard, `reads-${name}-${sanitizeId(table)}`, "reads_from", {
            kind: "entity",
            id: `dataset:${sanitizeId(table)}`
          });
      if (projectEntity)
        link(projectEntity, `owns-dashboard-${name}`, "owns", {
          kind: "entity",
          id: dashboard
        });
      break;
    }
    case "set_table_policy": {
      const table = sanitizeId(input.table_name ?? "");
      if (!table) break;
      ensureEntity(`dataset:${table}`, "dataset", input.table_name, {
        source_kind: "lance_table",
        collection: input.collection ?? null,
        sql_alias: input.sql_alias ?? null
      });
      break;
    }
    default:
      break;
  }
  return plan;
}
function refLabel(ref) {
  if (!ref || typeof ref !== "object") return "";
  const version = ref.version ? `@${ref.version}` : "";
  return `${ref.kind}:${ref.id}${version}`;
}
function activityOf(event) {
  if (event.type !== "session.event") return null;
  const d = event.data ?? {};
  if (d.event && typeof d.event === "object") {
    const ag = d.event;
    if (ag.type === "TOOL_CALL_START")
      return {
        type: "tool.call",
        tool: ag.toolCallName,
        label: ag.toolCallName
      };
    if (ag.type === "TOOL_CALL_RESULT") {
      const output = parseMaybeJson(ag.content);
      const error = toolError(output);
      return {
        type: "tool.result",
        tool: ag.toolCallName ?? null,
        label: null,
        error,
        output
      };
    }
    if (ag.type === "RUN_STARTED")
      return { type: "user.prompt", label: ag.input?.message ?? "" };
    if (ag.type === "CUSTOM" && ag.name === "lakeday.learning.required")
      return { type: "learning.nudge", label: ag.value?.reason ?? "" };
    if (ag.type === "CUSTOM" && ag.name === "lakeday.context.compacted")
      return { type: "compaction", label: "context compacted" };
    return null;
  }
  return { ...d, type: d.type ?? "event" };
}
var goalComponent = {
  name: "goal",
  initial: () => ({ goal: null, participants: [] }),
  reduce(state, event) {
    if (event.type !== "session.created") return state;
    const d = event.data ?? {};
    return {
      ...state,
      goal: d.goal ?? null,
      participants: d.participants ?? []
    };
  },
  view(state) {
    return state.goal ? [`Goal: ${clip(state.goal)}`] : [];
  }
};
var contextComponent = {
  name: "context",
  initial: () => ({ latest: null, compactions: 0 }),
  reduce(state, event) {
    if (event.type !== "session.context") return state;
    const d = event.data ?? {};
    return {
      latest: d,
      compactions: state.compactions + (d.reason === "compaction" ? 1 : 0)
    };
  },
  view(state) {
    if (!state.latest) return [];
    const lines = [];
    if (state.latest.summary)
      lines.push(`Working context: ${clip(state.latest.summary, 600)}`);
    if (Array.isArray(state.latest.plan) && state.latest.plan.length)
      lines.push(
        `Plan: ${state.latest.plan.map((s) => clip(s, 80)).join(" \u2192 ")}`
      );
    if (Array.isArray(state.latest.open) && state.latest.open.length)
      lines.push(
        `Open: ${state.latest.open.map((s) => clip(s, 100)).join("; ")}`
      );
    if (Array.isArray(state.latest.references) && state.latest.references.length)
      lines.push(
        `References: ${state.latest.references.slice(0, 8).map(refLabel).join(", ")}`
      );
    return lines;
  }
};
var decisionsComponent = {
  name: "decisions",
  initial: () => ({ byId: /* @__PURE__ */ new Map(), order: [] }),
  reduce(state, event) {
    if (event.type === "decision.recorded") {
      const d = event.data ?? {};
      const byId = new Map(state.byId);
      byId.set(d.id, {
        id: d.id,
        choice: d.choice,
        rationale: d.rationale,
        subjects: d.subjects ?? [],
        alternatives: d.alternatives ?? [],
        evidence: d.evidence ?? [],
        outcomes: [],
        sequence: event.sequence
      });
      return { byId, order: [...state.order, d.id] };
    }
    if (event.type === "decision.outcome") {
      const d = event.data ?? {};
      const existing = state.byId.get(d.id);
      if (!existing) return state;
      const byId = new Map(state.byId);
      byId.set(d.id, {
        ...existing,
        outcomes: [
          ...existing.outcomes,
          { outcome: d.outcome, evidence: d.evidence ?? [] }
        ]
      });
      return { ...state, byId };
    }
    return state;
  },
  view(state) {
    if (!state.order.length) return [];
    const lines = ["Decisions in this session:"];
    for (const id of state.order.slice(-8)) {
      const d = state.byId.get(id);
      const status2 = d.outcomes.length ? `outcome: ${clip(d.outcomes.at(-1).outcome, 120)}` : "outcome: not yet measured";
      lines.push(`- ${d.id}: ${clip(d.choice, 140)} (${status2})`);
    }
    return lines;
  }
};
var datasetsComponent = {
  name: "datasets",
  initial: () => ({ refs: /* @__PURE__ */ new Map() }),
  reduce(state, event) {
    const d = event.data ?? {};
    const refs = new Map(state.refs);
    const collect = (list) => {
      for (const ref of Array.isArray(list) ? list : [])
        if (ref && (ref.kind === "dataset" || ref.kind === "url"))
          refs.set(`${ref.kind}:${ref.id}`, {
            ...ref,
            sequence: event.sequence
          });
    };
    collect(d.evidence);
    collect(d.references);
    if (d.target && (d.target.kind === "dataset" || d.target.kind === "url"))
      collect([d.target]);
    return refs.size === state.refs.size ? state : { refs };
  },
  view(state) {
    if (!state.refs.size) return [];
    const items = [...state.refs.values()].slice(-10).map(refLabel);
    return [`Datasets and sources referenced: ${items.join(", ")}`];
  }
};
var recentComponent = {
  name: "recent",
  initial: () => ({ events: [] }),
  reduce(state, event) {
    const a = activityOf(event);
    if (!a || a.type === "tool.call") return state;
    const entry = {
      type: a.type,
      label: a.label ?? a.text ?? a.tool ?? "",
      error: a.error ?? null,
      sequence: event.sequence
    };
    return { events: [...state.events, entry].slice(-12) };
  },
  view(state) {
    if (!state.events.length) return [];
    const lines = ["Recent activity:"];
    for (const e of state.events.slice(-6))
      lines.push(
        `- ${e.type}${e.label ? `: ${clip(e.label, 120)}` : ""}${e.error ? ` [error: ${clip(e.error, 80)}]` : ""}`
      );
    return lines;
  }
};
var uncertainComponent = {
  name: "uncertain",
  initial: () => ({ open: /* @__PURE__ */ new Map(), pending: [] }),
  reduce(state, event) {
    const a = activityOf(event);
    if (!a) return state;
    if (a.type === "tool.call")
      return { ...state, pending: [...state.pending, a.tool].slice(-32) };
    if (a.type !== "tool.result") return state;
    const tool = a.tool ?? state.pending[0] ?? null;
    const pending = a.tool ? state.pending : state.pending.slice(1);
    if (!tool) return { ...state, pending };
    const open = new Map(state.open);
    if (a.error) open.set(tool, clip(a.error, 120));
    else open.delete(tool);
    return { open, pending };
  },
  view(state) {
    if (!state.open.size) return [];
    return [
      `Unresolved tool errors (verify state before repeating): ${[...state.open].map(([tool, err]) => `${tool} \u2192 ${err}`).join("; ")}`
    ];
  }
};
var factsComponent = {
  name: "facts",
  initial: () => ({ active: /* @__PURE__ */ new Map() }),
  reduce(state, event) {
    const d = event.data ?? {};
    if (event.type === "fact.asserted") {
      const active = new Map(state.active);
      active.set(d.id, {
        predicate: d.predicate,
        value: d.value,
        sequence: event.sequence
      });
      return { active };
    }
    if (event.type === "fact.retracted") {
      const active = new Map(state.active);
      active.delete(d.id);
      return { active };
    }
    return state;
  },
  view(state, ctx = {}) {
    if (!state.active.size) return [];
    const lines = [`Known facts about ${ctx.projectEntity ?? "the project"}:`];
    for (const [, f] of [...state.active].slice(-10))
      lines.push(
        `- ${f.predicate}: ${clip(typeof f.value === "string" ? f.value : JSON.stringify(f.value), 160)}`
      );
    return lines;
  }
};
var SESSION_COMPONENTS = [
  goalComponent,
  contextComponent,
  decisionsComponent,
  datasetsComponent,
  recentComponent,
  uncertainComponent
];
function fold(components, events) {
  const states = new Map(components.map((c) => [c.name, c.initial()]));
  for (const event of events ?? [])
    for (const component of components)
      states.set(
        component.name,
        component.reduce(states.get(component.name), event)
      );
  return states;
}
function priorDecisionsView(rows, currentSessionId) {
  if (!Array.isArray(rows) || !rows.length) return [];
  const lines = ["Prior decisions about this project (other sessions):"];
  for (const row of rows.slice(0, 6)) {
    if (row.session_id === currentSessionId) continue;
    const outcome = row.outcome ? ` \u2192 ${clip(row.outcome, 100)}` : " \u2192 no outcome recorded";
    lines.push(
      `- ${row.session_id}/${row.decision_id}: ${clip(row.choice ?? row.label, 120)}${outcome}`
    );
  }
  return lines.length > 1 ? lines : [];
}
function renderContext({
  sessionId,
  projectEntity,
  tenant,
  parts,
  budget = 16e3
}) {
  const header = [
    "<lakeday-knowledge>",
    `Lakeday session: ${sessionId}${tenant ? ` (tenant ${tenant})` : ""}.${projectEntity ? ` Project entity: ${projectEntity}.` : ""}`,
    `Record decisions with session_decide before finishing a turn that changes data, pipelines, dashboards, or code. Record measured results with session_outcome.${projectEntity ? ` Record durable learnings with entity_fact on ${projectEntity}.` : ""}`
  ];
  const footer = ["</lakeday-knowledge>"];
  const sections = parts.filter((lines) => lines && lines.length);
  let body = [];
  for (const lines of sections) {
    const candidate = [...body, "", ...lines];
    if ([...header, ...candidate, ...footer].join("\n").length > budget) break;
    body = candidate;
  }
  return [...header, ...body, ...footer].join("\n");
}
function projectSession({
  sessionEvents,
  factEvents,
  priorDecisions,
  sessionId,
  projectEntity,
  tenant,
  budget
}) {
  const states = fold(SESSION_COMPONENTS, sessionEvents);
  const factState = fold([factsComponent], factEvents).get("facts");
  const ctx = { projectEntity };
  const parts = [
    goalComponent.view(states.get("goal"), ctx),
    contextComponent.view(states.get("context"), ctx),
    decisionsComponent.view(states.get("decisions"), ctx),
    uncertainComponent.view(states.get("uncertain"), ctx),
    priorDecisionsView(priorDecisions, sessionId),
    factsComponent.view(factState, ctx),
    datasetsComponent.view(states.get("datasets"), ctx),
    recentComponent.view(states.get("recent"), ctx)
  ];
  return {
    states,
    text: renderContext({ sessionId, projectEntity, tenant, parts, budget })
  };
}
function summarizeForContext(states, { reason, turnSummary } = {}) {
  const decisions = states.get("decisions");
  const datasets = states.get("datasets");
  const uncertain = states.get("uncertain");
  const goal = states.get("goal");
  return {
    reason: reason ?? "turn",
    goal: goal.goal ?? null,
    summary: clip(turnSummary ?? "", 1200),
    decisions: decisions.order.slice(-8).map((id) => {
      const d = decisions.byId.get(id);
      return {
        id,
        choice: clip(d.choice, 160),
        measured: d.outcomes.length > 0
      };
    }),
    datasets: [...datasets.refs.values()].slice(-10).map(({ kind, id, version }) => ({
      kind,
      id,
      ...version ? { version } : {}
    })),
    open: [...uncertain.open].map(([tool, err]) => `${tool}: ${err}`),
    updated_at: (/* @__PURE__ */ new Date()).toISOString()
  };
}
function stopVerdict(turn, {
  enforce = true,
  maxNudges = 1,
  stopActive = false,
  sessionId,
  openDecisions = 0,
  measuredAfterDecision = false
} = {}) {
  if (!enforce) return { block: false };
  if (stopActive || (turn.nudges ?? turn.stopBlocks ?? 0) >= maxNudges)
    return { block: false, reason: "nudge budget exhausted" };
  const consequential = turn.tools.filter(
    (t) => t.kind === "consequential" && t.ok
  );
  const code = turn.tools.filter((t) => t.kind === "code");
  const needsDecision = (consequential.length > 0 || code.length >= 3) && (turn.decisions ?? 0) === 0;
  const needsOutcome = openDecisions > 0 && measuredAfterDecision && (turn.outcomes ?? 0) === 0;
  if (!needsDecision && !needsOutcome) return { block: false };
  const lines = [
    "Lakeday ALWAYS policy: this turn is not finished until its knowledge is recorded."
  ];
  if (needsDecision) {
    const effects = [
      ...consequential.map((t) => t.label),
      ...code.length ? [`${code.length} code edits`] : []
    ].slice(0, 6);
    lines.push(
      `You performed consequential actions without recording a decision: ${effects.join("; ")}.`,
      `Call session_decide${sessionId ? ` with id="${sessionId}"` : ""} and {id: <short-kebab-id>, subjects: [entity ids affected], choice: <what you did>, rationale: <why>, alternatives: [<what you rejected>], evidence: [{kind:"dataset", id:<table>, version:<snapshot if known>}]}.`,
      "Use one decision per independent choice. Then finish your reply.",
      "If no session_decide tool is available to you, end your reply with a fenced code block whose info string is lakeday-decision and whose body is that JSON object (one block per decision); the Lakeday hook records it for you."
    );
  }
  if (needsOutcome)
    lines.push(
      `A prior decision${sessionId ? ` in session ${sessionId}` : ""} has no measured outcome, and this turn measured results. Call session_outcome with the decision's record_id and {outcome: <measured result>, evidence: [...]}.`,
      "If no session_outcome tool is available, end your reply with a fenced lakeday-outcome code block containing {decision_id, outcome, evidence}."
    );
  lines.push(
    "If nothing consequential actually happened, say so explicitly in one sentence and finish; the policy will not block again this turn."
  );
  return { block: true, reason: lines.join("\n") };
}
function extractKnowledgeBlocks(text, { max = 8 } = {}) {
  const out = { decisions: [], outcomes: [], facts: [] };
  if (typeof text !== "string" || !text.includes("```lakeday-")) return out;
  const re = /```lakeday-(decision|outcome|fact)[^\n]*\n([\s\S]*?)```/g;
  let m;
  let count = 0;
  while ((m = re.exec(text)) && count < max) {
    let value;
    try {
      value = JSON.parse(m[2].trim());
    } catch {
      continue;
    }
    if (!value || typeof value !== "object" || Array.isArray(value)) continue;
    count++;
    if (m[1] === "decision") {
      if (typeof value.id !== "string" || !Array.isArray(value.subjects) || !value.subjects.length || typeof value.choice !== "string" || typeof value.rationale !== "string")
        continue;
      out.decisions.push({
        id: sanitizeId(value.id, 128),
        subjects: value.subjects.slice(0, 64).map((s) => sanitizeId(s, 128)),
        choice: clip(value.choice, 2e3),
        rationale: clip(value.rationale, 4e3),
        ...Array.isArray(value.alternatives) ? {
          alternatives: value.alternatives.slice(0, 16).map((a) => clip(a, 500))
        } : {},
        ...Array.isArray(value.evidence) ? { evidence: value.evidence.slice(0, 32) } : {}
      });
    } else if (m[1] === "outcome") {
      if (typeof value.decision_id !== "string" || typeof value.outcome !== "string")
        continue;
      out.outcomes.push({
        decision_id: sanitizeId(value.decision_id, 128),
        outcome: clip(value.outcome, 2e3),
        ...Array.isArray(value.evidence) ? { evidence: value.evidence.slice(0, 32) } : {}
      });
    } else {
      if (typeof value.id !== "string" || typeof value.predicate !== "string" || !Object.hasOwn(value, "value"))
        continue;
      out.facts.push({
        id: sanitizeId(value.id, 128),
        predicate: clip(value.predicate, 200),
        value: typeof value.value === "string" ? clip(value.value, 4e3) : value.value,
        ...typeof value.entity === "string" ? { entity: sanitizeId(value.entity, 128) } : {},
        ...Array.isArray(value.evidence) ? { evidence: value.evidence.slice(0, 32) } : {}
      });
    }
  }
  return out;
}

// hooks/lib/adapters.mjs
function detectHarness(payload, env = process.env) {
  if (env.LAKEDAY_HOOK_HARNESS) return env.LAKEDAY_HOOK_HARNESS;
  if (payload && typeof payload.conversation_id === "string" && typeof payload.hook_event_name === "string" && /^[a-z]/.test(payload.hook_event_name)) return "cursor";
  if (payload && (typeof payload.turn_id === "string" || env.CODEX_HOME || env.CODEX_SANDBOX)) return "codex";
  return "claude";
}
var CURSOR_EVENTS = {
  sessionStart: "SessionStart",
  beforeSubmitPrompt: "UserPromptSubmit",
  afterMCPExecution: "PostToolUse",
  afterShellExecution: "PostToolUse",
  afterFileEdit: "PostToolUse",
  postToolUse: "PostToolUse",
  postToolUseFailure: "PostToolUse",
  stop: "Stop",
  preCompact: "PreCompact",
  sessionEnd: "SessionEnd"
};
function parseMaybeJson2(value) {
  if (typeof value !== "string") return value;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}
function normalize(payload, env = process.env) {
  const harness = detectHarness(payload, env);
  if (harness === "cursor") return normalizeCursor(payload);
  return normalizeClaudeLike(payload, harness);
}
function normalizeClaudeLike(p, harness) {
  const event = p.hook_event_name;
  const base = {
    harness,
    event: ["SessionStart", "UserPromptSubmit", "PostToolUse", "Stop", "PreCompact", "SessionEnd"].includes(event) ? event : "Ignored",
    sessionId: p.session_id ?? null,
    cwd: p.cwd ?? process.cwd(),
    transcriptPath: p.transcript_path ?? null,
    source: p.source ?? p.trigger ?? p.reason ?? null,
    stopActive: Boolean(p.stop_hook_active),
    raw: p
  };
  if (event === "UserPromptSubmit") base.prompt = typeof p.prompt === "string" ? p.prompt : "";
  if (event === "PostToolUse") {
    const output = p.tool_response ?? p.tool_output ?? p.result ?? null;
    base.tool = {
      name: p.tool_name ?? "",
      lakedayTool: lakedayToolName(p.tool_name),
      input: p.tool_input ?? {},
      output: parseMaybeJson2(output),
      error: toolError(output)
    };
  }
  return base;
}
function normalizeCursor(p) {
  const mapped = CURSOR_EVENTS[p.hook_event_name] ?? "Ignored";
  const cwd = p.cwd ?? (Array.isArray(p.workspace_roots) && p.workspace_roots[0]) ?? process.cwd();
  const base = {
    harness: "cursor",
    event: mapped,
    sessionId: p.conversation_id ?? p.session_id ?? null,
    cwd,
    transcriptPath: p.transcript_path ?? null,
    source: p.trigger ?? p.reason ?? null,
    stopActive: Number(p.loop_count ?? 0) > 0,
    raw: p
  };
  if (mapped === "UserPromptSubmit") base.prompt = typeof p.prompt === "string" ? p.prompt : "";
  if (mapped === "PostToolUse") {
    switch (p.hook_event_name) {
      case "afterMCPExecution": {
        const output = parseMaybeJson2(p.result_json);
        base.tool = { name: p.tool_name ?? "", serverName: p.mcp_server_name, lakedayTool: lakedayToolName(p.tool_name, p.mcp_server_name), input: p.tool_input ?? {}, output, error: toolError(output) };
        break;
      }
      case "afterShellExecution":
        base.tool = { name: "Bash", lakedayTool: null, input: { command: p.command ?? "" }, output: p.output ?? "", error: null };
        break;
      case "afterFileEdit":
        base.tool = { name: "Edit", lakedayTool: null, input: { file_path: p.file_path, edits: p.edits ?? [] }, output: null, error: null };
        break;
      case "postToolUseFailure":
        base.tool = { name: p.tool_name ?? "", lakedayTool: lakedayToolName(p.tool_name), input: p.tool_input ?? {}, output: null, error: p.error_message ?? "tool failed" };
        break;
      default:
        base.tool = { name: p.tool_name ?? "", lakedayTool: lakedayToolName(p.tool_name), input: p.tool_input ?? {}, output: parseMaybeJson2(p.tool_output), error: toolError(p.tool_output) };
    }
  }
  return base;
}
function encodeResponse(normalized, result) {
  const { harness, event } = normalized;
  if (!result) return { stdout: "", exitCode: 0 };
  if (harness === "cursor") return encodeCursor(normalized, result);
  const out = {};
  if (event === "Stop" && result.block) {
    out.decision = "block";
    out.reason = result.block.reason;
    return { stdout: JSON.stringify(out), exitCode: 0 };
  }
  if (result.additionalContext && (event === "SessionStart" || event === "UserPromptSubmit" || event === "PostToolUse")) {
    out.hookSpecificOutput = { hookEventName: event, additionalContext: result.additionalContext };
  }
  if (result.message) out.systemMessage = result.message;
  return { stdout: Object.keys(out).length ? JSON.stringify(out) : "", exitCode: 0 };
}
function encodeCursor(normalized, result) {
  const { event } = normalized;
  switch (event) {
    case "SessionStart":
      return { stdout: JSON.stringify({ additional_context: result.additionalContext ?? "" }), exitCode: 0 };
    case "UserPromptSubmit":
      return { stdout: JSON.stringify({ continue: true }), exitCode: 0 };
    case "PostToolUse":
      return { stdout: JSON.stringify(result.additionalContext ? { additional_context: result.additionalContext } : {}), exitCode: 0 };
    case "Stop":
      return { stdout: JSON.stringify(result.block ? { followup_message: result.block.reason } : {}), exitCode: 0 };
    case "PreCompact":
      return { stdout: JSON.stringify(result.message ? { user_message: result.message } : {}), exitCode: 0 };
    default:
      return { stdout: "", exitCode: 0 };
  }
}

// hooks/lib/client.mjs
import crypto from "node:crypto";
import fs3 from "node:fs";
import path3 from "node:path";
var LakedayError = class extends Error {
  constructor(status2, body, url) {
    super(`Lakeday ${status2} at ${url}: ${typeof body === "string" ? body.slice(0, 300) : JSON.stringify(body).slice(0, 300)}`);
    this.status = status2;
    this.body = body;
  }
};
function idempotencyKey(...parts) {
  return crypto.createHash("sha256").update(parts.map((p) => typeof p === "string" ? p : JSON.stringify(p)).join("\0")).digest("hex").slice(0, 40);
}
function sanitizeId2(value, max = 100) {
  const cleaned = String(value).replace(/[^a-zA-Z0-9_.:-]+/g, "-").replace(/^[^a-zA-Z0-9]+/, "");
  return (cleaned || "x").slice(0, max);
}
var LakedayClient = class {
  constructor(config, { fetch: fetchImpl = globalThis.fetch, log = () => {
  } } = {}) {
    this.config = config;
    this.fetch = fetchImpl;
    this.log = log;
    this.tenant = config.tenant;
    this.base = config.baseUrl;
    this.token = config.token;
    this.cacheFile = path3.join(config.home, "agent-skills", "cache", `${sanitizeId2(config.tenant)}.json`);
    this.cache = this.#readCache();
    this.owner = null;
  }
  #readCache() {
    try {
      return JSON.parse(fs3.readFileSync(this.cacheFile, "utf8"));
    } catch {
      return {};
    }
  }
  #writeCache() {
    try {
      fs3.mkdirSync(path3.dirname(this.cacheFile), { recursive: true });
      fs3.writeFileSync(this.cacheFile, JSON.stringify(this.cache));
    } catch {
    }
  }
  async request(pathname, { method = "GET", json, headers = {}, timeoutMs = 8e3 } = {}) {
    const url = `${this.base}${pathname}`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const response = await this.fetch(url, {
        method,
        headers: {
          authorization: `Bearer ${this.token}`,
          accept: "application/json",
          ...json !== void 0 ? { "content-type": "application/json" } : {},
          ...headers
        },
        body: json !== void 0 ? JSON.stringify(json) : void 0,
        signal: controller.signal
      });
      const text = await response.text();
      let body = text;
      try {
        body = text ? JSON.parse(text) : null;
      } catch {
      }
      this.log(`${method} ${pathname} -> ${response.status}`);
      if (!response.ok) throw new LakedayError(response.status, body, pathname);
      return body;
    } finally {
      clearTimeout(timer);
    }
  }
  /** Resolves (creating on first use) the caller's user Entity and owner prefix. */
  async me() {
    if (this.owner) return this.owner;
    const entity = await this.request(`/v1/os/tenants/${this.tenant}/entities/me`);
    const id = entity?.id ?? entity?.identity?.id ?? entity?.object_id;
    if (typeof id !== "string" || !id.endsWith("user")) throw new Error(`unexpected /entities/me response: ${JSON.stringify(entity).slice(0, 200)}`);
    this.owner = { prefix: id.slice(0, -"user".length), actor: id, entity };
    return this.owner;
  }
  /** Personal ID: owner prefix + suffix. */
  async personalId(suffix) {
    const { prefix } = await this.me();
    return `${prefix}${sanitizeId2(suffix, 120 - prefix.length)}`;
  }
  #objectPath(kind, id, operation = "") {
    const prefix = this.owner?.prefix;
    if (prefix && id.startsWith(prefix)) {
      return `/v1/os/tenants/${this.tenant}/${kind === "entity" ? "entities" : "sessions"}/${id}${operation}`;
    }
    return `/tenants/${this.tenant}/${kind}/${id}${operation}`;
  }
  async get(kind, id, operation = "") {
    try {
      return await this.request(this.#objectPath(kind, id, operation));
    } catch (error) {
      if (error instanceof LakedayError && error.status === 404) return null;
      throw error;
    }
  }
  async mutate(kind, id, operation, data, key) {
    return this.request(this.#objectPath(kind, id, operation), {
      method: "POST",
      json: data,
      headers: { "idempotency-key": key ?? idempotencyKey(kind, id, operation, data) }
    });
  }
  /** Ensures an object exists. Returns { created: boolean, object }. */
  async ensure(kind, id, data, key) {
    const existing = await this.get(kind, id);
    if (existing) return { created: false, object: existing };
    try {
      const object = await this.mutate(kind, id, "", data, key ?? `create-${sanitizeId2(id)}`);
      return { created: true, object };
    } catch (error) {
      if (error instanceof LakedayError && error.status === 409) return { created: false, object: await this.get(kind, id) };
      throw error;
    }
  }
  async history(kind, id, { after = 0, limit = 100, maxPages = 5 } = {}) {
    const events = [];
    let cursor = after;
    for (let page = 0; page < maxPages; page++) {
      const body = await this.get(kind, id, `/history?after=${cursor}&limit=${Math.min(limit, 100)}`);
      if (!body || !Array.isArray(body.events)) break;
      events.push(...body.events);
      if (body.next_after == null || body.events.length === 0) break;
      cursor = body.next_after;
      if (events.length >= limit) break;
    }
    return events;
  }
  async facts(kind, id, { limit = 100 } = {}) {
    const body = await this.get(kind, id, `/facts?after=0&limit=${Math.min(limit, 100)}`);
    return body?.events ?? [];
  }
  /** Read-only DataFusion SQL through the deployment's Query Worker. */
  async sql(sql, params, limit = 200) {
    return this.request(`/tenants/${this.tenant}/query/`, { method: "POST", json: { sql, ...params ? { params } : {}, limit } });
  }
  async endpoints() {
    if (this.cache.endpoints && Date.now() - (this.cache.endpointsAt ?? 0) < 6 * 3600 * 1e3) return this.cache.endpoints;
    const endpoints = await this.request(`/v1/deployments/${this.tenant}/endpoints`);
    this.cache.endpoints = endpoints;
    this.cache.endpointsAt = Date.now();
    this.#writeCache();
    return endpoints;
  }
};

// hooks/lib/transcript.mjs
import fs4 from "node:fs";
var MAX_BYTES = 2 * 1024 * 1024;
function readTranscriptTail(transcriptPath, { maxBytes = MAX_BYTES } = {}) {
  if (!transcriptPath) return [];
  let fd;
  try {
    const stat = fs4.statSync(transcriptPath);
    const start = Math.max(0, stat.size - maxBytes);
    fd = fs4.openSync(transcriptPath, "r");
    const buffer = Buffer.alloc(stat.size - start);
    fs4.readSync(fd, buffer, 0, buffer.length, start);
    const text = buffer.toString("utf8");
    const lines = text.split("\n");
    if (start > 0) lines.shift();
    const entries = [];
    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        entries.push(JSON.parse(line));
      } catch {
      }
    }
    return entries;
  } catch {
    return [];
  } finally {
    if (fd !== void 0) fs4.closeSync(fd);
  }
}
function textOf(message) {
  if (!message) return "";
  const content = message.content ?? message;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content.filter((c) => c && ["text", "output_text", "input_text"].includes(c.type) && typeof c.text === "string").map((c) => c.text).join("\n");
  }
  if (typeof content?.text === "string") return content.text;
  return "";
}
function roleOf(entry) {
  if (entry.type === "response_item") {
    const p = entry.payload ?? {};
    if (p.type === "message" && (p.role === "assistant" || p.role === "user")) return p.role;
    if (p.type === "function_call") return "assistant";
    if (p.type === "function_call_output") return "tool";
    return null;
  }
  if (entry.type === "assistant" || entry.role === "assistant" || entry.message?.role === "assistant") return "assistant";
  if (entry.type === "user" || entry.role === "user" || entry.message?.role === "user") return "user";
  if (entry.type === "message" && entry.payload?.role) return entry.payload.role;
  return null;
}
function lastAssistantTurn(transcriptPath) {
  const entries = readTranscriptTail(transcriptPath);
  const chunks = [];
  for (let i = entries.length - 1; i >= 0; i--) {
    const entry = entries[i];
    const role = roleOf(entry);
    const message = entry.message ?? entry.payload ?? entry;
    if (role === "user") {
      const text = textOf(message);
      const isToolResult = Array.isArray(message?.content) && message.content.some((c) => c?.type === "tool_result");
      if (text.trim() && !isToolResult) break;
      continue;
    }
    if (role === "assistant") {
      const text = textOf(message);
      if (text.trim()) chunks.unshift(text.trim());
    }
  }
  return chunks.join("\n\n");
}

// hooks/lib/state.mjs
import crypto2 from "node:crypto";
import fs5 from "node:fs";
import path4 from "node:path";
function sessionKey(harness, sessionId, cwd) {
  return crypto2.createHash("sha256").update(`${harness}\0${sessionId ?? ""}\0${cwd ?? ""}`).digest("hex").slice(0, 24);
}
function stateDir(home) {
  return path4.join(home, "agent-skills", "sessions");
}
function emptyTurn() {
  return { startedAt: (/* @__PURE__ */ new Date()).toISOString(), tools: [], decisions: 0, outcomes: 0, facts: 0, stopBlocks: 0, measuredAfterDecision: false };
}
function loadState(home, key) {
  const file = path4.join(stateDir(home), `${key}.json`);
  try {
    const state = JSON.parse(fs5.readFileSync(file, "utf8"));
    if (!state.turn) state.turn = emptyTurn();
    return state;
  } catch {
    return { key, lakedaySessionId: null, owner: null, projectEntity: null, turn: emptyTurn(), seq: 0, createdAt: (/* @__PURE__ */ new Date()).toISOString() };
  }
}
function saveState(home, state) {
  const dir = stateDir(home);
  fs5.mkdirSync(dir, { recursive: true });
  const file = path4.join(dir, `${state.key}.json`);
  const tmp = `${file}.${process.pid}.tmp`;
  fs5.writeFileSync(tmp, JSON.stringify(state));
  fs5.renameSync(tmp, file);
}
function nextSeq(state) {
  state.seq = (state.seq ?? 0) + 1;
  return state.seq;
}

// hooks/lakeday-hook.mjs
var PRIOR_DECISIONS_SQL = `
SELECT session_id, decision_id, actor_id, label AS choice, timestamp
FROM lk_knowledge
WHERE type = 'decision.recorded' AND row_kind = 'reference'
  AND target_kind = 'entity' AND target_id = $1
ORDER BY timestamp DESC
LIMIT 12`;
var OUTCOMES_SQL = `
SELECT session_id, decision_id, label AS outcome, timestamp
FROM lk_knowledge
WHERE type = 'decision.outcome' AND row_kind = 'event' AND session_id = ANY($1)
ORDER BY timestamp DESC
LIMIT 50`;
async function activate(config, { env = process.env, fetch: fetchImpl = globalThis.fetch, execFile: execFileImpl, cwd = process.cwd(), log = () => {
} } = {}) {
  if (!config.token) {
    const resolved = await resolveToken({ baseUrl: config.baseUrl, home: config.home, cwd, env, execFile: execFileImpl, log });
    config.token = resolved.token;
    config.tokenSource = resolved.source;
    if (!resolved.token) {
      config.reason = `no credential: ${resolved.hint}`;
      return config;
    }
  } else {
    config.tokenSource = "env";
  }
  if (!config.tenant) {
    try {
      config.tenant = await discoverTenant({ baseUrl: config.baseUrl, token: config.token, home: config.home, fetch: fetchImpl, log });
    } catch (error) {
      log(`tenant discovery failed: ${error.message}`);
    }
    if (!config.tenant) {
      config.reason = "no tenant: set tenant_id in .lakeday/agent-skills.json or LAKEDAY_TENANT_ID (more than one deployment is visible)";
      return config;
    }
  }
  config.enabled = true;
  return config;
}
async function run(payload, { env = process.env, fetch: fetchImpl, execFile: execFileImpl, now = () => /* @__PURE__ */ new Date() } = {}) {
  const normalized = normalize(payload, env);
  const config = resolveConfig({ cwd: normalized.cwd, env });
  const log = makeLogger(config);
  if (normalized.event === "Ignored") return { normalized, result: null };
  try {
    await activate(config, { env, fetch: fetchImpl ?? globalThis.fetch, execFile: execFileImpl, cwd: normalized.cwd, log });
  } catch (error) {
    log(`activation failed: ${error.message}`);
  }
  if (!config.enabled) {
    log(`disabled: ${config.reason}`);
    return { normalized, result: null };
  }
  const client = new LakedayClient(config, { fetch: fetchImpl, log });
  const key = sessionKey(normalized.harness, normalized.sessionId, normalized.cwd);
  const state = loadState(config.home, key);
  try {
    const result = await handle(normalized, { config, client, state, log, now });
    saveState(config.home, state);
    return { normalized, result };
  } catch (error) {
    log(`error: ${error?.stack ?? error}`);
    try {
      saveState(config.home, state);
    } catch {
    }
    return { normalized, result: null };
  }
}
async function ensureSession(normalized, { config, client, state, log }) {
  const owner = await client.me();
  state.owner = { prefix: owner.prefix, actor: owner.actor };
  if (!state.lakedaySessionId) {
    const short = sanitizeId(String(normalized.sessionId ?? "local").replace(/-/g, "").slice(0, 12), 12);
    state.lakedaySessionId = await client.personalId(`${normalized.harness}-${config.project}-${short}`);
  }
  if (!state.projectEntity) {
    state.projectEntity = config.sharedEntities ? config.projectEntity : await client.personalId(config.projectEntity.replace(/^repo:/, "repo-"));
  }
  const goal = `${normalized.harness} session in ${config.project}`;
  const { created } = await client.ensure("session", state.lakedaySessionId, {
    participants: [owner.actor],
    goal,
    harness: normalized.harness,
    cwd: normalized.cwd,
    project: config.project,
    project_entity: state.projectEntity,
    harness_session_id: normalized.sessionId
  });
  await client.ensure("entity", state.projectEntity, { type: "repo", name: config.project, actor_id: owner.actor });
  if (created) {
    log(`created session ${state.lakedaySessionId}`);
    await client.mutate("entity", state.projectEntity, "/relationships", {
      id: sanitizeId(`session-${state.lakedaySessionId}`),
      predicate: "worked_on_in",
      target: { kind: "session", id: state.lakedaySessionId },
      session_id: state.lakedaySessionId
    }, idempotencyKey("link-session", state.lakedaySessionId));
  }
  return state.lakedaySessionId;
}
async function projectedContext({ config, client, state, log }) {
  const sessionId = state.lakedaySessionId;
  const [sessionEvents, factEvents, priorDecisions] = await Promise.all([
    client.history("session", sessionId, { limit: 300 }).catch((e) => (log(`history failed: ${e.message}`), [])),
    client.facts("entity", state.projectEntity).catch((e) => (log(`facts failed: ${e.message}`), [])),
    config.recallPriorDecisions ? recallPriorDecisions(client, state.projectEntity, log) : Promise.resolve([])
  ]);
  return projectSession({
    sessionEvents,
    factEvents,
    priorDecisions,
    sessionId,
    projectEntity: state.projectEntity,
    tenant: config.tenant,
    budget: config.contextBudgetChars
  });
}
async function recallPriorDecisions(client, projectEntity, log) {
  try {
    const decisions = await client.sql(PRIOR_DECISIONS_SQL, [projectEntity], 12);
    const rows = rowsOf(decisions);
    if (!rows.length) return [];
    const sessions = [...new Set(rows.map((r) => r.session_id))];
    let outcomes = [];
    try {
      outcomes = rowsOf(await client.sql(OUTCOMES_SQL, [sessions], 50));
    } catch (e) {
      log(`outcomes recall failed: ${e.message}`);
    }
    return rows.map((r) => ({ ...r, outcome: outcomes.find((o) => o.session_id === r.session_id && o.decision_id === r.decision_id)?.outcome ?? null }));
  } catch (e) {
    log(`prior decision recall failed: ${e.message}`);
    return [];
  }
}
function rowsOf(result) {
  if (!result) return [];
  if (Array.isArray(result.rows) && Array.isArray(result.columns)) {
    return result.rows.map((row) => Array.isArray(row) ? Object.fromEntries(result.columns.map((c, i) => [typeof c === "string" ? c : c.name, row[i]])) : row);
  }
  return Array.isArray(result) ? result : [];
}
async function handle(normalized, ctx) {
  const { config, client, state, log } = ctx;
  switch (normalized.event) {
    case "SessionStart": {
      await ensureSession(normalized, ctx);
      state.turn = emptyTurn();
      if (normalized.source && normalized.source !== "startup") {
        await appendEvent(ctx, { type: "session.resumed", label: `${normalized.harness} ${normalized.source}` });
      }
      const projection = await projectedContext(ctx);
      return { additionalContext: projection.text };
    }
    case "UserPromptSubmit": {
      await ensureSession(normalized, ctx);
      state.turn = emptyTurn();
      await appendEvent(ctx, { type: "user.prompt", text: clip(normalized.prompt, 2e3), label: clip(normalized.prompt, 160) });
      const projection = await projectedContext(ctx);
      return { additionalContext: projection.text };
    }
    case "PostToolUse": {
      const tool = normalized.tool ? normalizeToolCall({ ...normalized.tool, serverName: normalized.tool.serverName }) : null;
      if (!tool) return null;
      const kind = classifyTool(tool);
      if (kind === "other") return null;
      await ensureSession(normalized, ctx);
      state.turn.tools.push({ name: tool.name, lakedayTool: tool.lakedayTool, kind, ok: !tool.error, label: clip(toolEventData(tool, normalized.harness).label, 120) });
      if (kind === "recording") {
        if (tool.lakedayTool === "session_decide" && !tool.error) state.turn.decisions++;
        if (tool.lakedayTool === "session_outcome" && !tool.error) state.turn.outcomes++;
        if (tool.lakedayTool === "entity_fact" && !tool.error) state.turn.facts++;
        return null;
      }
      if (kind === "measurement" && sessionHasOpenDecision(state)) state.turn.measuredAfterDecision = true;
      if (kind !== "read") {
        await appendEvent(ctx, toolEventData(tool, normalized.harness));
      } else if (tool.error) {
        await appendEvent(ctx, toolEventData(tool, normalized.harness));
      }
      const structured = tool.output && typeof tool.output === "object" ? tool.output.structuredContent ?? tool.output : null;
      const serverProvenance = structured && typeof structured.provenance === "object" && structured.provenance ? structured.provenance : null;
      const recorded = serverProvenance ? Array.isArray(serverProvenance.recorded) ? serverProvenance.recorded : [] : await executeProvenance(provenancePlan(tool, { sessionId: state.lakedaySessionId, projectEntity: state.projectEntity }), ctx);
      if (recorded.length) {
        return { additionalContext: `Lakeday recorded provenance: ${recorded.join(", ")}. Reference these entity ids as subjects when you record the decision.` };
      }
      return null;
    }
    case "Stop": {
      await ensureSession(normalized, ctx);
      const turnText = lastAssistantTurn(normalized.transcriptPath);
      await recordFencedBlocks(ctx, extractKnowledgeBlocks(turnText));
      const verdict = stopVerdict(state.turn, {
        enforce: config.enforceDecisions,
        maxNudges: config.maxStopBlocksPerTurn,
        stopActive: normalized.stopActive,
        sessionId: state.lakedaySessionId,
        openDecisions: state.openDecisions ?? 0,
        measuredAfterDecision: state.turn.measuredAfterDecision
      });
      if (verdict.block) {
        state.turn.stopBlocks++;
        log("blocking stop: decision required");
        return { block: { reason: verdict.reason } };
      }
      if (turnText) await appendEvent(ctx, { type: "assistant.turn", text: clip(turnText, 2e3), label: clip(turnText, 160) });
      await replaceContext(ctx, { reason: "turn", turnSummary: turnText });
      state.turn = emptyTurn();
      return null;
    }
    case "PreCompact": {
      await ensureSession(normalized, ctx);
      await replaceContext(ctx, { reason: "compaction", turnSummary: lastAssistantTurn(normalized.transcriptPath) });
      await appendEvent(ctx, { type: "compaction", label: `${normalized.harness} ${normalized.source ?? "compact"}` });
      return { message: "Lakeday saved the session context before compaction; the next prompt re-injects it." };
    }
    case "SessionEnd": {
      if (!state.lakedaySessionId) return null;
      await client.me();
      await appendEvent(ctx, { type: "session.ended", label: normalized.source ?? "end" });
      return null;
    }
    default:
      return null;
  }
}
function sessionHasOpenDecision(state) {
  return (state.openDecisions ?? 0) > 0 || state.turn.decisions > 0;
}
async function recordFencedBlocks({ client, state, log }, blocks) {
  state.recordedBlocks ??= [];
  const seen = new Set(state.recordedBlocks);
  const sessionId = state.lakedaySessionId;
  const actor = state.owner?.actor;
  for (const decision of blocks.decisions) {
    const key = `decision:${decision.id}`;
    if (seen.has(key)) continue;
    try {
      await client.mutate("session", sessionId, "/decisions", { ...decision, actor_id: actor }, idempotencyKey("fenced", sessionId, key));
      state.turn.decisions++;
      state.recordedBlocks.push(key);
      log(`recorded fenced decision ${decision.id}`);
    } catch (error) {
      if (error?.status === 409) {
        state.turn.decisions++;
        state.recordedBlocks.push(key);
      } else log(`fenced decision failed: ${error.message}`);
    }
  }
  for (const outcome of blocks.outcomes) {
    const key = `outcome:${outcome.decision_id}:${clip(outcome.outcome, 40)}`;
    if (seen.has(key)) continue;
    const { decision_id, ...data } = outcome;
    try {
      await client.mutate("session", sessionId, `/decisions/${encodeURIComponent(decision_id)}/outcomes`, { ...data, actor_id: actor }, idempotencyKey("fenced", sessionId, key));
      state.turn.outcomes++;
      state.recordedBlocks.push(key);
    } catch (error) {
      if (error?.status !== 409) log(`fenced outcome failed: ${error.message}`);
    }
  }
  for (const fact of blocks.facts) {
    const key = `fact:${fact.entity ?? "project"}:${fact.id}`;
    if (seen.has(key)) continue;
    const { entity, ...data } = fact;
    const target = entity ?? state.projectEntity;
    try {
      await client.mutate("entity", target, "/facts", { ...data, actor_id: actor, session_id: sessionId }, idempotencyKey("fenced", sessionId, key));
      state.turn.facts++;
      state.recordedBlocks.push(key);
    } catch (error) {
      if (error?.status !== 409) log(`fenced fact failed: ${error.message}`);
    }
  }
}
async function appendEvent({ client, state }, data) {
  const seq = nextSeq(state);
  const body = { ...data, seq };
  return client.mutate("session", state.lakedaySessionId, "/events", body, idempotencyKey("event", state.lakedaySessionId, seq, data.type, data.label ?? ""));
}
async function replaceContext(ctx, { reason, turnSummary }) {
  const { client, state, log } = ctx;
  const events = await client.history("session", state.lakedaySessionId, { limit: 300 }).catch((e) => (log(`history failed: ${e.message}`), []));
  const states = fold(SESSION_COMPONENTS, events);
  const decisions = states.get("decisions");
  state.openDecisions = decisions.order.filter((id) => decisions.byId.get(id).outcomes.length === 0).length;
  const context = summarizeForContext(states, { reason, turnSummary });
  const seq = nextSeq(state);
  await client.mutate("session", state.lakedaySessionId, "/context", { ...context, seq }, idempotencyKey("context", state.lakedaySessionId, seq));
}
async function executeProvenance(plan, { client, state, log }) {
  const recorded = [];
  const owner = state.owner;
  for (const step of plan) {
    try {
      if (step.op === "ensure-entity") {
        const id = resolveEntityId(step.id, state, client);
        const { created } = await client.ensure("entity", id, { ...step.data, actor_id: owner.actor });
        if (created) recorded.push(id);
      } else if (step.op === "link") {
        const from = resolveEntityId(step.entity, state, client);
        const target = step.data.target.kind === "entity" ? { ...step.data.target, id: resolveEntityId(step.data.target.id, state, client) } : step.data.target;
        await client.mutate("entity", from, "/relationships", { ...step.data, target, actor_id: owner.actor }, idempotencyKey("link", from, step.data.id));
      }
    } catch (error) {
      if (error?.status === 409) continue;
      log(`provenance step failed (${step.op} ${step.id ?? step.entity}): ${error.message}`);
    }
  }
  return recorded;
}
function resolveEntityId(id, state, client) {
  if (id === state.projectEntity) return id;
  if (client.config.sharedEntities) return id;
  const prefix = state.owner?.prefix ?? "";
  if (id.startsWith(prefix)) return id;
  return `${prefix}${sanitizeId(id.replace(":", "-"), 120 - prefix.length)}`;
}
function makeLogger(config) {
  if (!config.debug) return () => {
  };
  const file = path5.join(config.home, "agent-skills", "hooks.log");
  return (line) => {
    try {
      fs6.mkdirSync(path5.dirname(file), { recursive: true });
      fs6.appendFileSync(file, `${(/* @__PURE__ */ new Date()).toISOString()} ${line}
`);
    } catch {
    }
  };
}
function login(args = [], { env = process.env, spawn: spawnImpl = nodeSpawn, stderr = process.stderr } = {}) {
  const child = spawnImpl(cliPath(env), ["login", ...args], {
    stdio: "inherit",
    env: { ...process.env, ...env }
  });
  return new Promise((resolve) => {
    let settled = false;
    const finish = (code) => {
      if (settled) return;
      settled = true;
      resolve(typeof code === "number" ? code : 1);
    };
    child.once("error", (error) => {
      stderr.write(`lk login failed (${safeErrorCode(error)})
`);
      finish(1);
    });
    child.once("exit", (code) => finish(code));
  });
}
async function status() {
  const config = resolveConfig({ env: process.env });
  await activate(config, { env: process.env, fetch: globalThis.fetch });
  process.stdout.write(JSON.stringify({ enabled: config.enabled, base_url: config.baseUrl, tenant: config.tenant, credential: config.tokenSource ?? "none", project: config.project, reason: config.reason ?? null }, null, 2) + "\n");
}
async function main() {
  const [command, ...rest] = process.argv.slice(2);
  if (command === "login") {
    process.exitCode = await login(rest);
    return;
  }
  if (command === "status" || command === "whoami") return status();
  let raw = "";
  for await (const chunk of process.stdin) raw += chunk;
  let payload = {};
  try {
    payload = raw.trim() ? JSON.parse(raw) : {};
  } catch {
    payload = {};
  }
  const { normalized, result } = await run(payload);
  const response = encodeResponse(normalized, result);
  if (response.stdout) process.stdout.write(response.stdout);
  process.exitCode = response.exitCode;
}
function isMainModule() {
  if (!process.argv[1]) return false;
  const modulePath = fileURLToPath(import.meta.url);
  try {
    return fs6.realpathSync(process.argv[1]) === fs6.realpathSync(modulePath);
  } catch {
    return path5.resolve(process.argv[1]) === modulePath;
  }
}
if (isMainModule()) {
  main().catch((error) => {
    if (process.argv[2] === "login" || process.argv[2] === "status" || process.argv[2] === "whoami") {
      process.stderr.write(`${error.message}
`);
      process.exitCode = 1;
    } else process.exitCode = 0;
  });
}
export {
  activate,
  login,
  run
};
