#!/usr/bin/env node
// Generates the per-harness plugin packages under plugins/ from the canonical
// skills/, hooks/, and mcp/ sources. Checked-in output; re-run after editing.

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { build as esbuild } from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const marketplace = JSON.parse(fs.readFileSync(path.join(root, ".claude-plugin", "marketplace.json"), "utf8"));
const version = pkg.version;

function rmrf(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else fs.copyFileSync(src, dst);
  }
}

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

function hookSourceFiles(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...hookSourceFiles(file));
    else if (entry.isFile() && entry.name.endsWith(".mjs")) files.push(file);
  }
  return files.sort();
}

const learningSource = fileURLToPath(import.meta.resolve("@lakeday-org/worker-js/learning"));
const hookBuildId = createHash("sha256")
  .update(fs.readFileSync(learningSource))
  .update("\0")
  .update(hookSourceFiles(path.join(root, "hooks")).map((file) => `${path.relative(root, file)}\0${fs.readFileSync(file)}`).join("\0"))
  .digest("hex")
  .slice(0, 16);
const hookBuildMarker = `// GENERATED by scripts/build-plugins.mjs; hook sources ${hookBuildId}\n`;

async function bundleHook(pluginDir) {
  const hookDir = path.join(pluginDir, "hooks");
  const outfile = path.join(hookDir, "lakeday-hook.mjs");
  fs.mkdirSync(hookDir, { recursive: true });
  await esbuild({
    entryPoints: [path.join(root, "hooks", "lakeday-hook.mjs")],
    outfile,
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    sourcemap: false,
    legalComments: "none",
    metafile: false,
  });
  const bundled = fs.readFileSync(outfile, "utf8");
  const newline = bundled.indexOf("\n");
  const shebang = bundled.startsWith("#!") && newline >= 0 ? bundled.slice(0, newline + 1) : "";
  const body = shebang ? bundled.slice(newline + 1) : bundled;
  fs.writeFileSync(outfile, `${shebang}${hookBuildMarker}${body}`);
  fs.chmodSync(outfile, 0o755);
}

function copyHookConfig(name, pluginDir) {
  const from = path.join(root, "hooks", name);
  const to = path.join(pluginDir, "hooks", name);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

// Keep every manifest on the package version.
marketplace.metadata.version = version;
for (const plugin of marketplace.plugins) plugin.version = version;
writeJson(path.join(root, ".claude-plugin", "marketplace.json"), marketplace);
for (const manifest of [".codex-plugin/plugin.json", ".cursor-plugin/plugin.json"]) {
  const file = path.join(root, manifest);
  const value = JSON.parse(fs.readFileSync(file, "utf8"));
  value.version = version;
  writeJson(file, value);
}

const description = marketplace.plugins[0].description;

// Claude Code plugin: skills + hooks + MCP server declaration.
const claudeDir = path.join(root, "plugins", "lakeday-skills-claude");
rmrf(claudeDir);
copyDir(path.join(root, "skills"), path.join(claudeDir, "skills"));
copyHookConfig("hooks.json", claudeDir);
await bundleHook(claudeDir);
const mcp = JSON.parse(fs.readFileSync(path.join(root, "mcp", "lakeday.mcp.json"), "utf8"));
writeJson(path.join(claudeDir, ".mcp.json"), mcp);
writeJson(path.join(claudeDir, ".claude-plugin", "plugin.json"), {
  name: "lakeday-skills",
  version,
  description,
  author: { name: "Lakeday", url: "https://lakeday.ai" },
  homepage: "https://github.com/lakeday-org/agent-skills",
  repository: "https://github.com/lakeday-org/agent-skills",
  license: "MIT",
  keywords: marketplace.plugins[0].tags,
  skills: "./skills/",
  hooks: "./hooks/hooks.json",
  mcpServers: "./.mcp.json",
});

// Codex plugin: same layout, hooks reference the plugin root variable.
const codexDir = path.join(root, "plugins", "lakeday-skills-codex");
rmrf(codexDir);
copyDir(path.join(root, "skills"), path.join(codexDir, "skills"));
copyHookConfig("hooks.json", codexDir);
await bundleHook(codexDir);
const codexHooks = JSON.parse(fs.readFileSync(path.join(root, "hooks", "hooks.json"), "utf8"));
const codexHooksText = JSON.stringify(codexHooks, null, 2).replaceAll("${CLAUDE_PLUGIN_ROOT}", "${CODEX_PLUGIN_ROOT}");
fs.writeFileSync(path.join(codexDir, "hooks", "hooks.json"), `${codexHooksText}\n`);
copyDir(path.join(root, "mcp"), path.join(codexDir, "mcp"));
const codexManifest = JSON.parse(fs.readFileSync(path.join(root, ".codex-plugin", "plugin.json"), "utf8"));
writeJson(path.join(codexDir, ".codex-plugin", "plugin.json"), codexManifest);

// Cursor plugin: skills + cursor hooks + MCP.
const cursorDir = path.join(root, "plugins", "lakeday-skills-cursor");
rmrf(cursorDir);
copyDir(path.join(root, "skills"), path.join(cursorDir, "skills"));
copyHookConfig("cursor.hooks.json", cursorDir);
await bundleHook(cursorDir);
copyDir(path.join(root, "mcp"), path.join(cursorDir, "mcp"));
writeJson(path.join(cursorDir, ".cursor-plugin", "plugin.json"), JSON.parse(fs.readFileSync(path.join(root, ".cursor-plugin", "plugin.json"), "utf8")));

console.log(`built plugins for version ${version}: claude, codex, cursor`);
