#!/usr/bin/env node
// GENERATED by scripts/build-plugins.mjs; hook sources 855b31fb0028e4a5

// hooks/lakeday-hook.mjs
import fs3 from "node:fs";
import path3 from "node:path";

// hooks/lib/config.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
function lakedayHome(env = process.env) {
  return env.LAKEDAY_HOME || path.join(os.homedir(), ".lakeday");
}
function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}
function findProjectConfig(cwd) {
  let dir = cwd ? path.resolve(cwd) : process.cwd();
  for (; ; ) {
    const candidate = path.join(dir, ".lakeday", "agent-skills.json");
    if (fs.existsSync(candidate)) return { file: candidate, dir, data: readJson(candidate) ?? {} };
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
function projectSlug(cwd) {
  const base = path.basename(path.resolve(cwd || process.cwd())) || "project";
  const slug = base.toLowerCase().replace(/[^a-z0-9_.-]+/g, "-").replace(/^[^a-z0-9]+/, "");
  return (slug || "project").slice(0, 60);
}
function resolveConfig({ cwd, env = process.env } = {}) {
  const project = findProjectConfig(cwd);
  const user = readJson(path.join(lakedayHome(env), "agent-skills.json")) ?? {};
  const merged = { ...user, ...project?.data ?? {} };
  const tenant = env.LAKEDAY_TENANT_ID || merged.tenant_id || null;
  const slug = merged.project || projectSlug(project?.dir ?? cwd);
  const config = {
    enabled: merged.enabled !== false && env.LAKEDAY_HOOKS !== "0",
    tenant,
    home: lakedayHome(env),
    project: slug,
    enforceDecisions: merged.enforce_decisions !== false,
    maxStopBlocksPerTurn: Number.isInteger(merged.max_stop_blocks_per_turn) ? merged.max_stop_blocks_per_turn : 1,
    debug: env.LAKEDAY_HOOK_DEBUG === "1" || merged.debug === true,
    sourceFiles: { project: project?.file ?? null, user: path.join(lakedayHome(env), "agent-skills.json") }
  };
  if (!config.enabled) config.reason = "hooks disabled by configuration";
  return config;
}

// ../../../../private/tmp/lakeday-tenantless/sdk/packages/worker-js/src/learning.js
var LEARNING_MODES = Object.freeze(["always", "agentic", "off"]);
var MAX_LINE = 240;
function clip(text, max = MAX_LINE) {
  if (text == null) return "";
  const single = String(text).replace(/\s+/g, " ").trim();
  return single.length > max ? `${single.slice(0, max - 1)}\u2026` : single;
}
function sanitizeId(value, max = 100) {
  const cleaned = String(value).replace(/[^a-zA-Z0-9_.:-]+/g, "-").replace(/^[^a-zA-Z0-9]+/, "");
  return (cleaned || "x").slice(0, max);
}
var CONSEQUENTIAL_TOOLS = /* @__PURE__ */ new Set([
  "deploy_worker",
  "delete_worker",
  "deploy_pipeline",
  "run_pipeline",
  "stream_send",
  "stream_load",
  "transform_commit",
  "sink_commit",
  "lake_ingest",
  "create_collection",
  "collection_grant",
  "assign_data_source",
  "set_table_policy",
  "create_dashboard",
  "update_dashboard",
  "delete_dashboard"
]);
var MEASUREMENT_TOOLS = /* @__PURE__ */ new Set([
  "query_sql",
  "inspect_dashboard",
  "evaluate_dashboard",
  "sink_read",
  "ui_render"
]);
var RECORDING_TOOLS = /* @__PURE__ */ new Set([
  "session_decide",
  "session_outcome",
  "entity_fact",
  "entity_link",
  "session_append",
  "session_context"
]);
var CODE_TOOLS = /* @__PURE__ */ new Set([
  "Edit",
  "Write",
  "MultiEdit",
  "NotebookEdit",
  "apply_patch"
]);
function normalizeToolCall({ name, input, output, error, serverName }) {
  let toolName = name ?? "";
  let toolInput = input && typeof input === "object" ? input : {};
  if (toolName === "product_tool" && typeof toolInput.name === "string") {
    toolName = toolInput.name;
    toolInput = toolInput.arguments && typeof toolInput.arguments === "object" ? toolInput.arguments : {};
  }
  const lakedayTool = lakedayToolName(toolName, serverName);
  const parsed = parseMaybeJson(output);
  return {
    name: toolName,
    lakedayTool,
    input: toolInput,
    output: parsed,
    error: error ?? toolError(parsed)
  };
}
function lakedayToolName(name, serverName) {
  if (!name) return null;
  if (serverName && serverName !== "lakeday") return null;
  let candidate = name;
  const mcp = /^mcp__([^_]+(?:_[^_]+)*)__(.+)$/.exec(name);
  if (mcp) {
    if (mcp[1] !== "lakeday") return null;
    candidate = mcp[2];
  } else if (name.includes("__")) {
    const parts = name.split("__");
    if (parts[0] !== "lakeday") return null;
    candidate = parts.slice(1).join("__");
  } else if (name.startsWith("lakeday.")) {
    candidate = name.slice("lakeday.".length);
  }
  if (CONSEQUENTIAL_TOOLS.has(candidate) || MEASUREMENT_TOOLS.has(candidate) || RECORDING_TOOLS.has(candidate) || /^(entity|session|query|stream|sink|transform|list|get|whoami|invoke|render|validate|package|ui|web|browser)_?[a-z_]*$/.test(
    candidate
  ))
    return candidate;
  return null;
}
function parseMaybeJson(value) {
  if (typeof value !== "string") return value;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}
function toolError(output) {
  if (output == null) return null;
  if (typeof output === "string")
    return /^(error|Error:|\{"error"|HTTP [45]\d\d)/m.test(output.trim()) ? output.slice(0, 500) : null;
  if (typeof output === "object") {
    if (output.isError === true || output.is_error === true)
      return summarize(output);
    if (typeof output.error === "string") return output.error.slice(0, 500);
    if (typeof output.status === "number" && output.status >= 400)
      return summarize(output);
    if (output.structuredContent && typeof output.structuredContent.error === "string")
      return output.structuredContent.error.slice(0, 500);
  }
  return null;
}
function summarize(value) {
  try {
    return JSON.stringify(value).slice(0, 500);
  } catch {
    return String(value).slice(0, 500);
  }
}
function classifyTool(tool) {
  if (!tool) return "other";
  if (tool.lakedayTool) {
    if (RECORDING_TOOLS.has(tool.lakedayTool)) return "recording";
    if (CONSEQUENTIAL_TOOLS.has(tool.lakedayTool)) return "consequential";
    if (MEASUREMENT_TOOLS.has(tool.lakedayTool)) return "measurement";
    return "read";
  }
  if (CODE_TOOLS.has(tool.name)) return "code";
  if (tool.name === "Bash" && typeof tool.input?.command === "string" && /\bgit\s+(commit|push|merge|rebase|tag)\b/.test(tool.input.command))
    return "consequential";
  return "other";
}
function tablesInSql(sql) {
  if (typeof sql !== "string") return [];
  const found = /* @__PURE__ */ new Set();
  const re = /\b(?:from|join)\s+([a-zA-Z_][a-zA-Z0-9_.]*)/gi;
  let m;
  while (m = re.exec(sql)) {
    const name = m[1].split(".").pop();
    if (!["select", "lateral", "unnest", "values"].includes(name.toLowerCase()))
      found.add(name);
  }
  return [...found].slice(0, 6);
}
function structuredOf(output) {
  if (!output || typeof output !== "object") return {};
  if (output.structuredContent && typeof output.structuredContent === "object")
    return output.structuredContent;
  return output;
}
function evidenceFor(tool) {
  const t = tool.lakedayTool;
  const input = tool.input ?? {};
  const structured = structuredOf(tool.output);
  const version = structured.table_version ?? structured.snapshot ?? structured.version ?? null;
  const refs = [];
  const dataset = (id, v) => refs.push({
    kind: "dataset",
    id: sanitizeId(id),
    ...v != null ? { version: String(v) } : {}
  });
  switch (t) {
    case "run_pipeline":
    case "deploy_pipeline":
      if (input.sink_table) dataset(input.sink_table, version);
      else if (structured.sink_table) dataset(structured.sink_table, version);
      break;
    case "sink_commit":
      if (input.batch?.table) dataset(input.batch.table, version);
      break;
    case "lake_ingest":
      if (input.table) dataset(input.table, version);
      break;
    case "stream_load":
      if (input.stream) dataset(input.stream, version);
      if (input.source ?? input.url)
        refs.push({
          kind: "url",
          id: String(input.source ?? input.url).slice(0, 120)
        });
      break;
    case "query_sql":
      for (const table of tablesInSql(input.sql)) dataset(table, version);
      break;
    case "inspect_dashboard":
    case "evaluate_dashboard":
    case "render_dashboard":
      if (input.id)
        refs.push({ kind: "entity", id: `dashboard:${sanitizeId(input.id)}` });
      break;
    default:
      break;
  }
  return refs.slice(0, 8);
}
function subjectsFor(tool) {
  const t = tool.lakedayTool;
  const input = tool.input ?? {};
  const out = [];
  if (t === "deploy_pipeline" || t === "run_pipeline")
    out.push(`pipeline:${sanitizeId(input.name ?? "")}`);
  if (t === "deploy_worker" || t === "delete_worker" || t === "invoke_worker")
    out.push(`worker:${sanitizeId(input.worker ?? "")}`);
  if (t === "create_dashboard")
    out.push(`dashboard:${sanitizeId(input.name ?? "")}`);
  if (t === "update_dashboard" || t === "delete_dashboard")
    out.push(`dashboard:${sanitizeId(input.id ?? "")}`);
  return out.filter((s) => !s.endsWith(":"));
}
function describeLakedayCall(name, input) {
  switch (name) {
    case "query_sql":
      return `query_sql: ${input.sql ?? ""}`;
    case "deploy_pipeline":
      return `deploy_pipeline ${input.name}: ${input.source_stream} \u2192 ${input.output_stream} \u2192 ${input.sink_table}`;
    case "run_pipeline":
      return `run_pipeline ${input.name}`;
    case "stream_send":
      return `stream_send ${input.stream}: ${Array.isArray(input.events) ? input.events.length : "?"} events`;
    case "stream_load":
      return `stream_load ${input.stream} \u2190 ${input.source ?? input.url ?? ""}`;
    case "lake_ingest":
      return `lake_ingest ${input.table}: ${Array.isArray(input.rows) ? input.rows.length : "?"} rows`;
    case "deploy_worker":
      return `deploy_worker ${input.worker}`;
    case "create_dashboard":
      return `create_dashboard ${input.name}`;
    case "update_dashboard":
      return `update_dashboard ${input.id}`;
    case "set_table_policy":
      return `set_table_policy ${input.collection}/${input.table_name} as ${input.sql_alias}`;
    case "collection_grant":
      return `collection_grant ${input.collection} ${input.role}${input.revoke ? " (revoke)" : ""} \u2192 ${input.email ?? input.membership_id ?? ""}`;
    case "assign_data_source":
      return `assign_data_source ${input.collection} \u2190 ${input.worker}/${input.binding}/${input.source_name ?? input.object ?? ""}`;
    case "invoke_worker":
      return `invoke_worker ${input.worker} ${input.method ?? "GET"} ${input.path ?? "/"}`;
    default:
      return `${name} ${clip(JSON.stringify(stripLarge(input)), 150)}`;
  }
}
function describeGenericCall(name, input) {
  if (name === "Bash") return `Bash: ${input.command ?? ""}`;
  if (CODE_TOOLS.has(name))
    return `${name}: ${input.file_path ?? input.path ?? ""}`;
  return `${name}`;
}
function stripLarge(input) {
  const out = {};
  for (const [k, v] of Object.entries(input ?? {})) {
    if (typeof v === "string" && v.length > 120) out[k] = `${v.slice(0, 117)}\u2026`;
    else if (Array.isArray(v)) out[k] = `[${v.length} items]`;
    else if (v && typeof v === "object") out[k] = "{\u2026}";
    else out[k] = v;
  }
  return out;
}
function toolEventData(tool, harness) {
  const input = tool.input ?? {};
  const label = tool.lakedayTool ? describeLakedayCall(tool.lakedayTool, input) : describeGenericCall(tool.name, input);
  const data = {
    type: "tool.result",
    tool: tool.lakedayTool ?? tool.name,
    ...harness ? { harness } : {},
    label: clip(label, 200),
    ok: !tool.error
  };
  if (tool.error) data.error = clip(tool.error, 300);
  const evidence = evidenceFor(tool);
  if (evidence.length) data.evidence = evidence;
  const subjects = subjectsFor(tool);
  if (subjects.length) data.subjects = subjects;
  return data;
}
function stopVerdict(turn, {
  enforce = true,
  maxNudges = 1,
  stopActive = false,
  sessionId,
  openDecisions = 0,
  measuredAfterDecision = false
} = {}) {
  if (!enforce) return { block: false };
  if (stopActive || (turn.nudges ?? turn.stopBlocks ?? 0) >= maxNudges)
    return { block: false, reason: "nudge budget exhausted" };
  const consequential = turn.tools.filter(
    (t) => t.kind === "consequential" && t.ok
  );
  const code = turn.tools.filter((t) => t.kind === "code");
  const needsDecision = (consequential.length > 0 || code.length >= 3) && (turn.decisions ?? 0) === 0;
  const needsOutcome = openDecisions > 0 && measuredAfterDecision && (turn.outcomes ?? 0) === 0;
  if (!needsDecision && !needsOutcome) return { block: false };
  const lines = [
    "Lakeday ALWAYS policy: this turn is not finished until its knowledge is recorded."
  ];
  if (needsDecision) {
    const effects = [
      ...consequential.map((t) => t.label),
      ...code.length ? [`${code.length} code edits`] : []
    ].slice(0, 6);
    lines.push(
      `You performed consequential actions without recording a decision: ${effects.join("; ")}.`,
      `Call session_decide${sessionId ? ` with id="${sessionId}"` : ""} and {id: <short-kebab-id>, subjects: [entity ids affected], choice: <what you did>, rationale: <why>, alternatives: [<what you rejected>], evidence: [{kind:"dataset", id:<table>, version:<snapshot if known>}]}.`,
      "Use one decision per independent choice. Then finish your reply."
    );
  }
  if (needsOutcome)
    lines.push(
      `A prior decision${sessionId ? ` in session ${sessionId}` : ""} has no measured outcome, and this turn measured results. Call session_outcome with the decision's record_id and {outcome: <measured result>, evidence: [...]}.`
    );
  lines.push(
    "If nothing consequential actually happened, say so explicitly in one sentence and finish; the policy will not block again this turn."
  );
  return { block: true, reason: lines.join("\n") };
}

// hooks/lib/adapters.mjs
var LAKEDAY_SERVER = /^lakeday(?:[-_].+)?$/;
function lakedayToolName2(name, serverName) {
  if (serverName !== void 0 && serverName !== null) {
    return LAKEDAY_SERVER.test(serverName) ? lakedayToolName(name, "lakeday") : null;
  }
  const mcp = /^mcp__([^_]+(?:_[^_]+)*)__(.+)$/.exec(name ?? "");
  if (mcp) return LAKEDAY_SERVER.test(mcp[1]) ? lakedayToolName(`mcp__lakeday__${mcp[2]}`) : null;
  return lakedayToolName(name);
}
function toolIdentity(name, serverName) {
  const lakedayName = lakedayToolName2(name, serverName);
  return { name: lakedayName ? `mcp__lakeday__${lakedayName}` : name ?? "", lakedayTool: lakedayName };
}
function detectHarness(payload, env = process.env) {
  if (env.LAKEDAY_HOOK_HARNESS) return env.LAKEDAY_HOOK_HARNESS;
  if (payload && typeof payload.conversation_id === "string" && typeof payload.hook_event_name === "string" && /^[a-z]/.test(payload.hook_event_name)) return "cursor";
  if (payload && (typeof payload.turn_id === "string" || env.CODEX_HOME || env.CODEX_SANDBOX)) return "codex";
  return "claude";
}
var CURSOR_EVENTS = {
  sessionStart: "SessionStart",
  beforeSubmitPrompt: "UserPromptSubmit",
  afterMCPExecution: "PostToolUse",
  afterShellExecution: "PostToolUse",
  afterFileEdit: "PostToolUse",
  postToolUse: "PostToolUse",
  postToolUseFailure: "PostToolUse",
  stop: "Stop",
  preCompact: "PreCompact",
  sessionEnd: "SessionEnd"
};
function parseMaybeJson2(value) {
  if (typeof value !== "string") return value;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}
function normalize(payload, env = process.env) {
  const harness = detectHarness(payload, env);
  if (harness === "cursor") return normalizeCursor(payload);
  return normalizeClaudeLike(payload, harness);
}
function normalizeClaudeLike(p, harness) {
  const event = p.hook_event_name;
  const base = {
    harness,
    event: ["SessionStart", "UserPromptSubmit", "PostToolUse", "Stop", "PreCompact", "SessionEnd"].includes(event) ? event : "Ignored",
    sessionId: p.session_id ?? null,
    cwd: p.cwd ?? process.cwd(),
    transcriptPath: p.transcript_path ?? null,
    source: p.source ?? p.trigger ?? p.reason ?? null,
    stopActive: Boolean(p.stop_hook_active),
    raw: p
  };
  if (event === "UserPromptSubmit") base.prompt = typeof p.prompt === "string" ? p.prompt : "";
  if (event === "PostToolUse") {
    const output = p.tool_response ?? p.tool_output ?? p.result ?? null;
    base.tool = {
      ...toolIdentity(p.tool_name),
      input: p.tool_input ?? {},
      output: parseMaybeJson2(output),
      error: toolError(output)
    };
  }
  return base;
}
function normalizeCursor(p) {
  const mapped = CURSOR_EVENTS[p.hook_event_name] ?? "Ignored";
  const cwd = p.cwd ?? (Array.isArray(p.workspace_roots) && p.workspace_roots[0]) ?? process.cwd();
  const base = {
    harness: "cursor",
    event: mapped,
    sessionId: p.conversation_id ?? p.session_id ?? null,
    cwd,
    transcriptPath: p.transcript_path ?? null,
    source: p.trigger ?? p.reason ?? null,
    stopActive: Number(p.loop_count ?? 0) > 0,
    raw: p
  };
  if (mapped === "UserPromptSubmit") base.prompt = typeof p.prompt === "string" ? p.prompt : "";
  if (mapped === "PostToolUse") {
    switch (p.hook_event_name) {
      case "afterMCPExecution": {
        const output = parseMaybeJson2(p.result_json);
        base.tool = { ...toolIdentity(p.tool_name, p.mcp_server_name), input: p.tool_input ?? {}, output, error: toolError(output) };
        break;
      }
      case "afterShellExecution":
        base.tool = { name: "Bash", lakedayTool: null, input: { command: p.command ?? "" }, output: p.output ?? "", error: null };
        break;
      case "afterFileEdit":
        base.tool = { name: "Edit", lakedayTool: null, input: { file_path: p.file_path, edits: p.edits ?? [] }, output: null, error: null };
        break;
      case "postToolUseFailure":
        base.tool = { ...toolIdentity(p.tool_name), input: p.tool_input ?? {}, output: null, error: p.error_message ?? "tool failed" };
        break;
      default:
        base.tool = { ...toolIdentity(p.tool_name), input: p.tool_input ?? {}, output: parseMaybeJson2(p.tool_output), error: toolError(p.tool_output) };
    }
  }
  return base;
}
function encodeResponse(normalized, result) {
  const { harness, event } = normalized;
  if (!result) return { stdout: "", exitCode: 0 };
  if (harness === "cursor") return encodeCursor(normalized, result);
  const out = {};
  if (event === "Stop" && result.block) {
    out.decision = "block";
    out.reason = result.block.reason;
    return { stdout: JSON.stringify(out), exitCode: 0 };
  }
  if (result.additionalContext && (event === "SessionStart" || event === "UserPromptSubmit" || event === "PostToolUse")) {
    out.hookSpecificOutput = { hookEventName: event, additionalContext: result.additionalContext };
  }
  if (result.message) out.systemMessage = result.message;
  return { stdout: Object.keys(out).length ? JSON.stringify(out) : "", exitCode: 0 };
}
function encodeCursor(normalized, result) {
  const { event } = normalized;
  switch (event) {
    case "SessionStart":
      return { stdout: JSON.stringify({ additional_context: result.additionalContext ?? "" }), exitCode: 0 };
    case "UserPromptSubmit":
      return { stdout: JSON.stringify({ continue: true }), exitCode: 0 };
    case "PostToolUse":
      return { stdout: JSON.stringify(result.additionalContext ? { additional_context: result.additionalContext } : {}), exitCode: 0 };
    case "Stop":
      return { stdout: JSON.stringify(result.block ? { followup_message: result.block.reason } : {}), exitCode: 0 };
    case "PreCompact":
      return { stdout: JSON.stringify(result.message ? { user_message: result.message } : {}), exitCode: 0 };
    default:
      return { stdout: "", exitCode: 0 };
  }
}

// hooks/lib/state.mjs
import crypto from "node:crypto";
import fs2 from "node:fs";
import path2 from "node:path";
function sessionKey(harness, sessionId, cwd) {
  return crypto.createHash("sha256").update(`${harness}\0${sessionId ?? ""}\0${cwd ?? ""}`).digest("hex").slice(0, 24);
}
function stateDir(home) {
  return path2.join(home, "agent-skills", "sessions");
}
function emptyTurn() {
  return { startedAt: (/* @__PURE__ */ new Date()).toISOString(), tools: [], decisions: 0, outcomes: 0, facts: 0, stopBlocks: 0, measuredAfterDecision: false };
}
function loadState(home, key) {
  const file = path2.join(stateDir(home), `${key}.json`);
  try {
    const state = JSON.parse(fs2.readFileSync(file, "utf8"));
    if (!state.turn) state.turn = emptyTurn();
    return state;
  } catch {
    return { key, lakedaySessionId: null, owner: null, projectEntity: null, turn: emptyTurn(), seq: 0, createdAt: (/* @__PURE__ */ new Date()).toISOString() };
  }
}
function saveState(home, state) {
  const dir = stateDir(home);
  fs2.mkdirSync(dir, { recursive: true });
  const file = path2.join(dir, `${state.key}.json`);
  const tmp = `${file}.${process.pid}.tmp`;
  fs2.writeFileSync(tmp, JSON.stringify(state));
  fs2.renameSync(tmp, file);
}

// hooks/lakeday-hook.mjs
async function run(payload, { env = process.env } = {}) {
  const normalized = normalize(payload, env);
  if (normalized.event === "Ignored") return { normalized, result: null };
  const config = resolveConfig({ cwd: normalized.cwd, env });
  const log = makeLogger(config);
  if (!config.enabled) {
    log(`disabled: ${config.reason}`);
    return { normalized, result: null };
  }
  const key = sessionKey(normalized.harness, normalized.sessionId, normalized.cwd);
  const state = loadState(config.home, key);
  if (!state.sessionKeyName) {
    const short = sanitizeId(String(normalized.sessionId ?? "local").replace(/-/g, "").slice(0, 12), 12);
    state.sessionKeyName = sanitizeId(`${normalized.harness}-${config.project}-${short}`, 80);
  }
  try {
    const result = handle(normalized, { config, state, log });
    saveState(config.home, state);
    return { normalized, result };
  } catch (error) {
    log(`error: ${error?.stack ?? error}`);
    try {
      saveState(config.home, state);
    } catch {
    }
    return { normalized, result: null };
  }
}
function openInstruction(config, state, { prompt } = {}) {
  const tenant = config.tenant ? `"${config.tenant}"` : "the deployment id from list_deployments";
  const lines = ["<lakeday-hooks>"];
  if (state.lakedaySessionId) {
    lines.push(
      `Lakeday session: ${state.lakedaySessionId}${state.projectEntity ? ` (project entity ${state.projectEntity})` : ""}.`,
      `Before working on this request, call the Lakeday MCP tool session_project with tenant_id ${tenant}, id "${state.lakedaySessionId}"${state.projectEntity ? `, project_entity "${state.projectEntity}"` : ""} and read the returned <lakeday-knowledge> block as the projected state of this session.`
    );
  } else {
    lines.push(
      `Before working on this request, call the Lakeday MCP tool session_open with tenant_id ${tenant}, key "${state.sessionKeyName}", project "${config.project}"${prompt ? `, goal ${JSON.stringify(clip(prompt, 200))}` : ""}. It creates or resumes your personal session and returns its id plus a <lakeday-knowledge> block; treat that block as the projected state of this session.`,
      "If the Lakeday MCP server is not connected, or it exposes no session_open, say so once and continue without it."
    );
  }
  lines.push(
    "Record every consequential choice this turn (deployments, ingestion, dashboards, grants, code changes, commits) with session_decide on that session: id, subjects, choice, rationale, alternatives, evidence with dataset versions. Record measured results of earlier decisions with session_outcome, durable facts with entity_fact on the project entity. The turn cannot finish with unrecorded consequential actions.",
    "</lakeday-hooks>"
  );
  return lines.join("\n");
}
function handle(normalized, { config, state, log }) {
  switch (normalized.event) {
    case "SessionStart":
      state.turn = emptyTurn();
      return { additionalContext: openInstruction(config, state) };
    case "UserPromptSubmit":
      state.turn = emptyTurn();
      return { additionalContext: openInstruction(config, state, { prompt: normalized.prompt }) };
    case "PostToolUse": {
      const tool = normalized.tool ? normalizeToolCall({ ...normalized.tool, serverName: normalized.tool.serverName }) : null;
      if (!tool) return null;
      learnSession(state, tool, log);
      const kind = classifyTool(tool);
      if (kind === "other") return null;
      state.turn.tools.push({ name: tool.name, lakedayTool: tool.lakedayTool, kind, ok: !tool.error, label: clip(toolEventData(tool, normalized.harness).label, 120) });
      if (kind === "recording" && !tool.error) {
        if (tool.lakedayTool === "session_decide") {
          state.turn.decisions++;
          state.openDecisions = (state.openDecisions ?? 0) + 1;
        }
        if (tool.lakedayTool === "session_outcome") {
          state.turn.outcomes++;
          state.openDecisions = Math.max(0, (state.openDecisions ?? 0) - 1);
        }
        if (tool.lakedayTool === "entity_fact") state.turn.facts++;
      }
      if (kind === "measurement" && (state.openDecisions ?? 0) > 0) state.turn.measuredAfterDecision = true;
      return null;
    }
    case "Stop": {
      const verdict = stopVerdict(state.turn, {
        enforce: config.enforceDecisions,
        maxNudges: config.maxStopBlocksPerTurn,
        stopActive: normalized.stopActive,
        sessionId: state.lakedaySessionId ?? void 0,
        openDecisions: state.openDecisions ?? 0,
        measuredAfterDecision: state.turn.measuredAfterDecision
      });
      if (verdict.block) {
        state.turn.nudges = (state.turn.nudges ?? 0) + 1;
        log("blocking stop: decision required");
        const reason = state.lakedaySessionId ? verdict.reason : `${verdict.reason}
No Lakeday session is open yet: call session_open with key "${state.sessionKeyName}" and project "${config.project}" first, then session_decide on the returned session id.`;
        return { block: { reason } };
      }
      state.turn = emptyTurn();
      return null;
    }
    case "PreCompact":
      return { message: "Lakeday: the next prompt re-projects the session from durable events through session_project; nothing depends on the transcript surviving compaction." };
    default:
      return null;
  }
}
function learnSession(state, tool, log) {
  if (tool.lakedayTool !== "session_open" && tool.lakedayTool !== "session_project") return;
  const output = tool.output && typeof tool.output === "object" ? tool.output : {};
  const structured = output.structuredContent && typeof output.structuredContent === "object" ? output.structuredContent : output;
  let sessionId = typeof structured.session_id === "string" ? structured.session_id : null;
  let projectEntity = typeof structured.project_entity === "string" ? structured.project_entity : null;
  if (!sessionId) {
    const text = typeof tool.output === "string" ? tool.output : Array.isArray(output.content) ? output.content.map((c) => c?.text ?? "").join("\n") : JSON.stringify(output);
    const match = /Lakeday session: ([A-Za-z0-9][A-Za-z0-9_.:-]*)/.exec(text);
    if (match) sessionId = match[1];
    const project = /Project entity: ([A-Za-z0-9][A-Za-z0-9_.:-]*)\./.exec(text);
    if (project) projectEntity = project[1];
  }
  if (sessionId && sessionId !== state.lakedaySessionId) {
    state.lakedaySessionId = sessionId;
    log(`session ${sessionId}`);
  }
  if (projectEntity) state.projectEntity = projectEntity;
}
function makeLogger(config) {
  if (!config.debug) return () => {
  };
  const file = path3.join(config.home, "agent-skills", "hooks.log");
  return (line) => {
    try {
      fs3.mkdirSync(path3.dirname(file), { recursive: true });
      fs3.appendFileSync(file, `${(/* @__PURE__ */ new Date()).toISOString()} ${line}
`);
    } catch {
    }
  };
}
async function status() {
  const config = resolveConfig({ env: process.env });
  process.stdout.write(`${JSON.stringify({ enabled: config.enabled, tenant: config.tenant ?? null, project: config.project, reason: config.reason ?? null, home: config.home }, null, 2)}
`);
}
async function main() {
  const [command] = process.argv.slice(2);
  if (command === "status") return status();
  let raw = "";
  for await (const chunk of process.stdin) raw += chunk;
  let payload = {};
  try {
    payload = raw.trim() ? JSON.parse(raw) : {};
  } catch {
    payload = {};
  }
  const { normalized, result } = await run(payload);
  const response = encodeResponse(normalized, result);
  if (response.stdout) process.stdout.write(response.stdout);
  process.exitCode = response.exitCode;
}
if (process.argv[1] && path3.resolve(process.argv[1]) === new URL(import.meta.url).pathname) {
  main().catch(() => {
    process.exitCode = 0;
  });
}
export {
  openInstruction,
  run
};
